package defpackage;

import android.view.ViewGroup;
import java.util.Arrays;
import java.util.HashMap;

/* compiled from: r8-map-id-826db3e0ccd5eff4e36cfb5c0bfeee0451562e7e7652a4d6d90edd453ef96714 */
/* loaded from: classes.dex */
public final class cz4 {
    public int a;
    public final fz4 b;
    public final ez4 c;
    public final dz4 d;
    public final gz4 e;
    public HashMap f;

    /* JADX WARN: Type inference failed for: r0v0, types: [fz4, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r0v1, types: [java.lang.Object, ez4] */
    /* JADX WARN: Type inference failed for: r0v2, types: [java.lang.Object, dz4] */
    /* JADX WARN: Type inference failed for: r0v3, types: [gz4, java.lang.Object] */
    public cz4() {
        ?? obj = new Object();
        obj.a = 0;
        obj.b = 0;
        obj.c = 1.0f;
        obj.d = Float.NaN;
        this.b = obj;
        ?? obj2 = new Object();
        obj2.a = -1;
        obj2.b = 0;
        obj2.c = -1;
        obj2.d = Float.NaN;
        obj2.e = Float.NaN;
        obj2.f = Float.NaN;
        obj2.g = -1;
        obj2.h = null;
        obj2.i = -1;
        this.c = obj2;
        ?? obj3 = new Object();
        obj3.a = false;
        obj3.d = -1;
        obj3.e = -1;
        obj3.f = -1.0f;
        obj3.g = true;
        obj3.h = -1;
        obj3.i = -1;
        obj3.j = -1;
        obj3.k = -1;
        obj3.l = -1;
        obj3.m = -1;
        obj3.n = -1;
        obj3.o = -1;
        obj3.p = -1;
        obj3.q = -1;
        obj3.r = -1;
        obj3.s = -1;
        obj3.t = -1;
        obj3.u = -1;
        obj3.v = -1;
        obj3.w = 0.5f;
        obj3.x = 0.5f;
        obj3.y = null;
        obj3.z = -1;
        obj3.A = 0;
        obj3.B = 0.0f;
        obj3.C = -1;
        obj3.D = -1;
        obj3.E = -1;
        obj3.F = 0;
        obj3.G = 0;
        obj3.H = 0;
        obj3.I = 0;
        obj3.J = 0;
        obj3.K = 0;
        obj3.L = 0;
        obj3.M = Integer.MIN_VALUE;
        obj3.N = Integer.MIN_VALUE;
        obj3.O = Integer.MIN_VALUE;
        obj3.P = Integer.MIN_VALUE;
        obj3.Q = Integer.MIN_VALUE;
        obj3.R = Integer.MIN_VALUE;
        obj3.S = Integer.MIN_VALUE;
        obj3.T = -1.0f;
        obj3.U = -1.0f;
        obj3.V = 0;
        obj3.W = 0;
        obj3.X = 0;
        obj3.Y = 0;
        obj3.Z = 0;
        obj3.a0 = 0;
        obj3.b0 = 0;
        obj3.c0 = 0;
        obj3.d0 = 1.0f;
        obj3.e0 = 1.0f;
        obj3.f0 = -1;
        obj3.g0 = 0;
        obj3.h0 = -1;
        obj3.l0 = false;
        obj3.m0 = false;
        obj3.n0 = true;
        obj3.o0 = 0;
        this.d = obj3;
        ?? obj4 = new Object();
        obj4.a = 0.0f;
        obj4.b = 0.0f;
        obj4.c = 0.0f;
        obj4.d = 1.0f;
        obj4.e = 1.0f;
        obj4.f = Float.NaN;
        obj4.g = Float.NaN;
        obj4.h = -1;
        obj4.i = 0.0f;
        obj4.j = 0.0f;
        obj4.k = 0.0f;
        obj4.l = false;
        obj4.m = 0.0f;
        this.e = obj4;
        this.f = new HashMap();
    }

    public final void a(xy4 xy4Var) {
        dz4 dz4Var = this.d;
        xy4Var.e = dz4Var.h;
        xy4Var.f = dz4Var.i;
        xy4Var.g = dz4Var.j;
        xy4Var.h = dz4Var.k;
        xy4Var.i = dz4Var.l;
        xy4Var.j = dz4Var.m;
        xy4Var.k = dz4Var.n;
        xy4Var.l = dz4Var.o;
        xy4Var.m = dz4Var.p;
        xy4Var.n = dz4Var.q;
        xy4Var.o = dz4Var.r;
        xy4Var.s = dz4Var.s;
        xy4Var.t = dz4Var.t;
        xy4Var.u = dz4Var.u;
        xy4Var.v = dz4Var.v;
        ((ViewGroup.MarginLayoutParams) xy4Var).leftMargin = dz4Var.F;
        ((ViewGroup.MarginLayoutParams) xy4Var).rightMargin = dz4Var.G;
        ((ViewGroup.MarginLayoutParams) xy4Var).topMargin = dz4Var.H;
        ((ViewGroup.MarginLayoutParams) xy4Var).bottomMargin = dz4Var.I;
        xy4Var.A = dz4Var.R;
        xy4Var.B = dz4Var.Q;
        xy4Var.x = dz4Var.N;
        xy4Var.z = dz4Var.P;
        xy4Var.E = dz4Var.w;
        xy4Var.F = dz4Var.x;
        xy4Var.p = dz4Var.z;
        xy4Var.q = dz4Var.A;
        xy4Var.r = dz4Var.B;
        xy4Var.G = dz4Var.y;
        xy4Var.T = dz4Var.C;
        xy4Var.U = dz4Var.D;
        xy4Var.I = dz4Var.T;
        xy4Var.H = dz4Var.U;
        xy4Var.K = dz4Var.W;
        xy4Var.J = dz4Var.V;
        xy4Var.W = dz4Var.l0;
        xy4Var.X = dz4Var.m0;
        xy4Var.L = dz4Var.X;
        xy4Var.M = dz4Var.Y;
        xy4Var.P = dz4Var.Z;
        xy4Var.Q = dz4Var.a0;
        xy4Var.N = dz4Var.b0;
        xy4Var.O = dz4Var.c0;
        xy4Var.R = dz4Var.d0;
        xy4Var.S = dz4Var.e0;
        xy4Var.V = dz4Var.E;
        xy4Var.c = dz4Var.f;
        xy4Var.a = dz4Var.d;
        xy4Var.b = dz4Var.e;
        ((ViewGroup.MarginLayoutParams) xy4Var).width = dz4Var.b;
        ((ViewGroup.MarginLayoutParams) xy4Var).height = dz4Var.c;
        String str = dz4Var.k0;
        if (str != null) {
            xy4Var.Y = str;
        }
        xy4Var.Z = dz4Var.o0;
        xy4Var.setMarginStart(dz4Var.K);
        xy4Var.setMarginEnd(dz4Var.J);
        xy4Var.a();
    }

    public final Object clone() {
        cz4 cz4Var = new cz4();
        dz4 dz4Var = this.d;
        boolean z = dz4Var.a;
        dz4 dz4Var2 = cz4Var.d;
        dz4Var2.a = z;
        dz4Var2.b = dz4Var.b;
        dz4Var2.c = dz4Var.c;
        dz4Var2.d = dz4Var.d;
        dz4Var2.e = dz4Var.e;
        dz4Var2.f = dz4Var.f;
        dz4Var2.g = dz4Var.g;
        dz4Var2.h = dz4Var.h;
        dz4Var2.i = dz4Var.i;
        dz4Var2.j = dz4Var.j;
        dz4Var2.k = dz4Var.k;
        dz4Var2.l = dz4Var.l;
        dz4Var2.m = dz4Var.m;
        dz4Var2.n = dz4Var.n;
        dz4Var2.o = dz4Var.o;
        dz4Var2.p = dz4Var.p;
        dz4Var2.q = dz4Var.q;
        dz4Var2.r = dz4Var.r;
        dz4Var2.s = dz4Var.s;
        dz4Var2.t = dz4Var.t;
        dz4Var2.u = dz4Var.u;
        dz4Var2.v = dz4Var.v;
        dz4Var2.w = dz4Var.w;
        dz4Var2.x = dz4Var.x;
        dz4Var2.y = dz4Var.y;
        dz4Var2.z = dz4Var.z;
        dz4Var2.A = dz4Var.A;
        dz4Var2.B = dz4Var.B;
        dz4Var2.C = dz4Var.C;
        dz4Var2.D = dz4Var.D;
        dz4Var2.E = dz4Var.E;
        dz4Var2.F = dz4Var.F;
        dz4Var2.G = dz4Var.G;
        dz4Var2.H = dz4Var.H;
        dz4Var2.I = dz4Var.I;
        dz4Var2.J = dz4Var.J;
        dz4Var2.K = dz4Var.K;
        dz4Var2.L = dz4Var.L;
        dz4Var2.M = dz4Var.M;
        dz4Var2.N = dz4Var.N;
        dz4Var2.O = dz4Var.O;
        dz4Var2.P = dz4Var.P;
        dz4Var2.Q = dz4Var.Q;
        dz4Var2.R = dz4Var.R;
        dz4Var2.S = dz4Var.S;
        dz4Var2.T = dz4Var.T;
        dz4Var2.U = dz4Var.U;
        dz4Var2.V = dz4Var.V;
        dz4Var2.W = dz4Var.W;
        dz4Var2.X = dz4Var.X;
        dz4Var2.Y = dz4Var.Y;
        dz4Var2.Z = dz4Var.Z;
        dz4Var2.a0 = dz4Var.a0;
        dz4Var2.b0 = dz4Var.b0;
        dz4Var2.c0 = dz4Var.c0;
        dz4Var2.d0 = dz4Var.d0;
        dz4Var2.e0 = dz4Var.e0;
        dz4Var2.f0 = dz4Var.f0;
        dz4Var2.g0 = dz4Var.g0;
        dz4Var2.h0 = dz4Var.h0;
        dz4Var2.k0 = dz4Var.k0;
        int[] iArr = dz4Var.i0;
        if (iArr != null && dz4Var.j0 == null) {
            dz4Var2.i0 = Arrays.copyOf(iArr, iArr.length);
        } else {
            dz4Var2.i0 = null;
        }
        dz4Var2.j0 = dz4Var.j0;
        dz4Var2.l0 = dz4Var.l0;
        dz4Var2.m0 = dz4Var.m0;
        dz4Var2.n0 = dz4Var.n0;
        dz4Var2.o0 = dz4Var.o0;
        ez4 ez4Var = this.c;
        int i = ez4Var.a;
        ez4 ez4Var2 = cz4Var.c;
        ez4Var2.a = i;
        ez4Var2.c = ez4Var.c;
        ez4Var2.e = ez4Var.e;
        ez4Var2.d = ez4Var.d;
        fz4 fz4Var = this.b;
        int i2 = fz4Var.a;
        fz4 fz4Var2 = cz4Var.b;
        fz4Var2.a = i2;
        fz4Var2.c = fz4Var.c;
        fz4Var2.d = fz4Var.d;
        fz4Var2.b = fz4Var.b;
        gz4 gz4Var = this.e;
        float f = gz4Var.a;
        gz4 gz4Var2 = cz4Var.e;
        gz4Var2.a = f;
        gz4Var2.b = gz4Var.b;
        gz4Var2.c = gz4Var.c;
        gz4Var2.d = gz4Var.d;
        gz4Var2.e = gz4Var.e;
        gz4Var2.f = gz4Var.f;
        gz4Var2.g = gz4Var.g;
        gz4Var2.h = gz4Var.h;
        gz4Var2.i = gz4Var.i;
        gz4Var2.j = gz4Var.j;
        gz4Var2.k = gz4Var.k;
        gz4Var2.l = gz4Var.l;
        gz4Var2.m = gz4Var.m;
        cz4Var.a = this.a;
        return cz4Var;
    }
}
