package defpackage;

import bo.app.u4;
import io.intercom.android.sdk.metrics.MetricTracker;
import io.radar.sdk.RadarTrackingOptions;
import java.util.LinkedHashMap;
import java.util.Map;
import kotlin.Lazy;
import kotlin.LazyKt;
import kotlin.collections.CollectionsKt;
import okhttp3.internal.http.HttpStatusCodesKt;
import okhttp3.internal.ws.WebSocketProtocol;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* compiled from: r8-map-id-826db3e0ccd5eff4e36cfb5c0bfeee0451562e7e7652a4d6d90edd453ef96714 */
/* loaded from: classes.dex */
public final class fq5 {
    private static final /* synthetic */ ug7 $ENTRIES;
    private static final /* synthetic */ fq5[] $VALUES;
    public static final fq5 ADM_MESSAGING_REGISTRATION_ENABLED;
    public static final fq5 AD_TRACKING_ENABLED;
    public static final fq5 API_KEY;
    public static final fq5 AUTOMATIC_LOCATION_COLLECTION;
    public static final fq5 BANNERS;
    public static final fq5 BANNERS_DISMISSALS_CACHE_SIZE;
    public static final fq5 BANNERS_ENABLED;
    public static final fq5 BANNERS_IMPRESSION_MAP;
    public static final fq5 BANNERS_LAST_REQUEST_TIME_PER_PLACEMENT;
    public static final fq5 BANNERS_PENDING_DISMISSALS;
    public static final fq5 BLOCKLISTED_ATTRIBUTES;
    public static final fq5 BLOCKLISTED_EVENTS;
    public static final fq5 BLOCKLISTED_PURCHASES;
    public static final fq5 CACHED_DEVICE;
    public static final fq5 CONFIG_TIME;
    public static final fq5 CONTENT_CARDS;
    public static final fq5 CONTENT_CARDS_ENABLED;
    public static final fq5 CONTENT_CARDS_UNREAD_VISUAL_INDICATOR_ENABLED;
    public static final fq5 CONTENT_CARDS_UPDATED_LISTENER_CALLBACK_METHOD_NAME;
    public static final fq5 CONTENT_CARDS_UPDATED_LISTENER_GAME_OBJECT_NAME;
    public static final fq5 CURRENT_OPEN_SESSION_ID;
    public static final fq5 CUSTOM_ENDPOINT;
    public static final fq5 CUSTOM_HTML_WEBVIEW_ACTIVITY_CLASS_NAME;
    public static final fq5 CUSTOM_LOCATION_PROVIDERS_LIST;
    public static final u4 Companion;
    public static final fq5 DATA_SYNC_BAD_NETWORK_INTERVAL;
    public static final fq5 DATA_SYNC_GOOD_NETWORK_INTERVAL;
    public static final fq5 DATA_SYNC_GREAT_NETWORK_INTERVAL;
    public static final fq5 DEFAULT_NOTIFICATION_ACCENT_COLOR;
    public static final fq5 DEFAULT_NOTIFICATION_CHANNEL_DESCRIPTION;
    public static final fq5 DEFAULT_NOTIFICATION_CHANNEL_NAME;
    public static final fq5 DEFAULT_REQUEST_BACKOFF_MAX_SLEEP_DURATION_MS;
    public static final fq5 DEFAULT_REQUEST_BACKOFF_MIN_SLEEP_DURATION_MS;
    public static final fq5 DEFAULT_REQUEST_BACKOFF_SCALE_FACTOR;
    public static final fq5 DELAYED_INIT_ANALYTICS_BEHAVIOR_FLAG;
    public static final fq5 DELAYED_INIT_ENABLED;
    public static final fq5 DELAYED_INIT_SET_DURING_RUNTIME_FLAG;
    public static final fq5 DEVICE_CACHE_LAST_OS_VERSION;
    public static final fq5 DEVICE_CACHE_SEND_FULL_ON_NEXT_EXPORT;
    public static final fq5 DEVICE_ID;
    public static final fq5 DEVICE_OBJECT_ALLOWLIST;
    public static final fq5 DEVICE_OBJECT_ALLOWLISTING_ENABLED;
    public static final fq5 DISMISSED_CARDS;
    public static final fq5 DOES_PUSH_STORY_DISMISS_ON_CLICK;
    public static final fq5 DUST_AUTH;
    public static final fq5 DUST_AUTH_EXPIRATION_SECONDS;
    public static final fq5 DUST_ENABLED;
    public static final fq5 DUST_HOST;
    public static final fq5 DUST_RCS;
    public static final fq5 DUST_SHOULD_BLOCK_CC_REFRESH;
    public static final fq5 ENDPOINT_ATTEMPT_COUNT_MAP;
    public static final fq5 ENDPOINT_LAST_REQUEST_MAP;
    public static final fq5 EPHEMERAL_EVENTS_ENABLED;
    public static final fq5 EVENT_DUPLICATION_VALIDATION_STORAGE_MAP;
    public static final fq5 EVENT_STORAGE_MAP;
    public static final fq5 EXPIRED_CARDS;
    public static final fq5 FALLBACK_FCM_SERVICE_CLASSPATH;
    public static final fq5 FALLBACK_FCM_SERVICE_ENABLED;
    public static final fq5 FEATURE_FLAGS;
    public static final fq5 FEATURE_FLAGS_ENABLED;
    public static final fq5 FEATURE_FLAGS_IMPRESSIONS_MAP;
    public static final fq5 FEATURE_FLAGS_RATE_REFRESH_RATE_LIMIT;
    public static final fq5 FEATURE_FLAGS_UPDATED_LISTENER_CALLBACK_METHOD_NAME;
    public static final fq5 FEATURE_FLAGS_UPDATED_LISTENER_GAME_OBJECT_NAME;
    public static final fq5 FIREBASE_CLOUD_MESSAGING_REGISTRATION_ENABLED;
    public static final fq5 FIREBASE_CLOUD_MESSAGING_SENDER_ID;
    public static final fq5 FIREBASE_MESSAGING_SERVICE_AUTOMATICALLY_REGISTER_ON_NEW_TOKEN;
    public static final fq5 GEOFENCES;
    public static final fq5 GEOFENCES_AUTOMATIC_REQUESTS_ENABLED;
    public static final fq5 GEOFENCES_ENABLED;
    public static final fq5 GEOFENCES_ENABLED_CONFIG;
    public static final fq5 GEOFENCES_ENABLED_SET;
    public static final fq5 GEOFENCES_MAX_NUM_TO_REGISTER;
    public static final fq5 GEOFENCES_MIN_TIME_REPORT;
    public static final fq5 GEOFENCES_MIN_TIME_REQUEST;
    public static final fq5 GLOBAL_LAST_REPORT;
    public static final fq5 GLOBAL_LAST_REQUEST;
    public static final fq5 GLOBAL_REQUEST_RATE_LIMITING_CAPACITY;
    public static final fq5 GLOBAL_REQUEST_RATE_LIMITING_ENABLED;
    public static final fq5 GLOBAL_REQUEST_RATE_LIMITING_REFILL_RATE;
    public static final fq5 GLOBAL_REQUEST_RATE_LIMIT_ENDPOINT_OVERRIDES;
    public static final fq5 GOOGLE_ADVERTISING_ID;
    public static final fq5 HANDLE_PUSH_DEEP_LINKS_AUTOMATICALLY;
    public static final fq5 HTML_IN_APP_MESSAGE_APPLY_WINDOW_INSETS;
    public static final fq5 HTML_IN_APP_MESSAGE_ENABLE_HTML_LINK_TARGET;
    public static final fq5 INAPP_AUTO_SET_MANAGER_LISTENER;
    public static final fq5 INAPP_INITIAL_DISPLAY_OPERATION;
    public static final fq5 INAPP_LISTENER_CALLBACK_METHOD_NAME;
    public static final fq5 INAPP_LISTENER_GAME_OBJECT_NAME;
    public static final fq5 INAPP_SHOW_INAPP_MESSAGES_AUTOMATICALLY;
    public static final fq5 INDIVIDUAL_REELIGIBILITY_MAP;
    public static final fq5 IN_APP_MESSAGE_ACCESSIBILITY_EXCLUSIVE_MODE_ENABLED;
    public static final fq5 IN_APP_MESSAGE_ADD_STATUS_BAR_PADDING;
    public static final fq5 IN_APP_MESSAGE_PUSH_TEST_EAGER_DISPLAY;
    public static final fq5 IN_APP_MESSAGE_WEBVIEW_CLIENT_MAX_ONPAGEFINISHED_WAIT;
    public static final fq5 LARGE_NOTIFICATION_ICON;
    public static final fq5 LAST_ACCESSED_SDK_VERSION;
    public static final fq5 LAST_CARD_STORAGE_UPDATE_TIMESTAMP;
    public static final fq5 LAST_CARD_UPDATED_AT;
    public static final fq5 LAST_FULL_CARD_SYNC_AT;
    public static final fq5 LAST_REFRESH_IN_SECONDS;
    public static final fq5 LAST_USER_ID;
    public static final fq5 LEGACY_DEVICE_ID;
    public static final fq5 MAX_BANNER_PLACEMENTS;
    public static final fq5 MESSAGING_SESSION_END_TIMESTAMP;
    public static final fq5 MESSAGING_SESSION_TIMEOUT;
    public static final fq5 MINIMUM_SESSION_TIMEOUT;
    public static final fq5 MITE_KEY;
    public static final fq5 OPTIN_WHEN_PUSH_AUTHORIZED;
    public static final fq5 PERMISSION_REQUEST_COUNTS;
    public static final fq5 PERSISTENT_DEVICE_ID;
    public static final fq5 PERSIST_IAM_WEBVIEW_WHEN_BACKGROUNDING_APP;
    public static final fq5 PUSH_DEEP_LINK_BACK_STACK_ACTIVITY_CLASS_NAME;
    public static final fq5 PUSH_DEEP_LINK_BACK_STACK_ACTIVITY_ENABLED;
    public static final fq5 PUSH_DELETED_CALLBACK_METHOD_NAME;
    public static final fq5 PUSH_DELETED_GAME_OBJECT_NAME;
    public static final fq5 PUSH_DELIVERY_EVENTS;
    public static final fq5 PUSH_ID_MAP;
    public static final fq5 PUSH_MAX_CAMPAIGNS;
    public static final fq5 PUSH_MAX_ENABLED;
    public static final fq5 PUSH_MAX_LAST_UPDATE;
    public static final fq5 PUSH_MAX_REDELIVER_BUFFER;
    public static final fq5 PUSH_MAX_REDELIVER_DEDUPE_BUFFER;
    public static final fq5 PUSH_NOTIFICATION_HTML_RENDERING_ENABLED;
    public static final fq5 PUSH_OPENED_CALLBACK_METHOD_NAME;
    public static final fq5 PUSH_OPENED_GAME_OBJECT_NAME;
    public static final fq5 PUSH_RECEIVED_CALLBACK_METHOD_NAME;
    public static final fq5 PUSH_RECEIVED_GAME_OBJECT_NAME;
    public static final fq5 PUSH_REGISTRATION_ID_KEY;
    public static final fq5 PUSH_REGISTRATION_PERSISTENT_DEVICE_ID;
    public static final fq5 PUSH_REGISTRATION_VERSION_CODE;
    public static final fq5 PUSH_TOKEN;
    public static final fq5 PUSH_WAKE_SCREEN_FOR_NOTIFICATION_ENABLED;
    public static final fq5 REGISTERED_GEOFENCES;
    public static final fq5 REQUIRE_TOUCH_MODE_FOR_HTML_IAMS;
    public static final fq5 SDK_AUTH;
    public static final fq5 SDK_AUTHENTICATION_FAILURE_LISTENER_CALLBACK_METHOD_NAME;
    public static final fq5 SDK_AUTHENTICATION_FAILURE_LISTENER_GAME_OBJECT_NAME;
    public static final fq5 SDK_AUTH_ENABLED;
    public static final fq5 SDK_DEBUGGER_AUTHORIZATION_CODE;
    public static final fq5 SDK_DEBUGGER_ENABLED;
    public static final fq5 SDK_DEBUGGER_EXPIRATION_TIME;
    public static final fq5 SDK_DEBUGGER_FLUSH_INTERVAL_BYTES;
    public static final fq5 SDK_DEBUGGER_FLUSH_INTERVAL_SECONDS;
    public static final fq5 SDK_DEBUGGER_MAX_PAYLOAD_BYTES;
    public static final fq5 SDK_ENABLEMENT;
    public static final fq5 SDK_FLAVOR;
    public static final fq5 SDK_METADATA;
    public static final fq5 SDK_METADATA_CONFIG;
    public static final fq5 SERIALIZED_USER_OBJECT;
    public static final fq5 SERVER_TARGET;
    public static final fq5 SESSION_START_BASED_TIMEOUT_ENABLED;
    public static final fq5 SESSION_STORAGE_MAP;
    public static final fq5 SESSION_TIMEOUT;
    public static final fq5 SMALL_NOTIFICATION_ICON;
    public static final fq5 SUFFIX_CACHE_USER_ID_HASH;
    public static final fq5 SUFFIX_CACHE_USER_ID_KEY;
    public static final fq5 TEST_BOOLEAN_KEY;
    public static final fq5 TEST_BOOLEAN_KEY_2;
    public static final fq5 TEST_CARDS;
    public static final fq5 TEST_DOUBLE_KEY;
    public static final fq5 TEST_ENUM_STRING_KEY;
    public static final fq5 TEST_FLOAT_KEY;
    public static final fq5 TEST_FLOAT_KEY_2;
    public static final fq5 TEST_INT_KEY;
    public static final fq5 TEST_INT_KEY_2;
    public static final fq5 TEST_LIST_KEY;
    public static final fq5 TEST_LONG_KEY;
    public static final fq5 TEST_LONG_KEY_2;
    public static final fq5 TEST_MAP_KEY;
    public static final fq5 TEST_STRING_KEY;
    public static final fq5 TEST_STRING_KEY_2;
    public static final fq5 TEST_STRING_SET_KEY;
    public static final fq5 TOKEN_BUCKET_CURRENT_TOKEN_COUNT;
    public static final fq5 TOKEN_BUCKET_LAST_CALL_AT_MS;
    public static final fq5 TRIGGERED_ACTIONS;
    public static final fq5 TRIGGERED_ACTIONS_IMPRESSION_MAP;
    public static final fq5 TRIGGERS_CHECKSUM;
    public static final fq5 TRIGGER_ACTION_MINIMUM_TIME_INTERVAL_SECONDS;
    public static final fq5 USE_WINDOW_FLAG_SECURE_IN_ACTIVITIES;
    private static final Lazy<Map<String, fq5>> keyMap$delegate;
    private final String key;
    private final sq5 type;

    static {
        sq5 sq5Var = sq5.LIST;
        fq5 fq5Var = new fq5("GEOFENCES", 0, "geofences", sq5Var);
        GEOFENCES = fq5Var;
        fq5 fq5Var2 = new fq5("REGISTERED_GEOFENCES", 1, "registered_geofences", sq5Var);
        REGISTERED_GEOFENCES = fq5Var2;
        sq5 sq5Var2 = sq5.LONG;
        fq5 fq5Var3 = new fq5("GLOBAL_LAST_REQUEST", 2, "last_request_global", sq5Var2);
        GLOBAL_LAST_REQUEST = fq5Var3;
        fq5 fq5Var4 = new fq5("GLOBAL_LAST_REPORT", 3, "last_report_global", sq5Var2);
        GLOBAL_LAST_REPORT = fq5Var4;
        sq5 sq5Var3 = sq5.MAP;
        fq5 fq5Var5 = new fq5("INDIVIDUAL_REELIGIBILITY_MAP", 4, "individual_reeligibility_map", sq5Var3);
        INDIVIDUAL_REELIGIBILITY_MAP = fq5Var5;
        fq5 fq5Var6 = new fq5("FEATURE_FLAGS", 5, "feature_flags", sq5Var);
        FEATURE_FLAGS = fq5Var6;
        fq5 fq5Var7 = new fq5("LAST_REFRESH_IN_SECONDS", 6, "last_refresh", sq5Var2);
        LAST_REFRESH_IN_SECONDS = fq5Var7;
        fq5 fq5Var8 = new fq5("FEATURE_FLAGS_IMPRESSIONS_MAP", 7, "ff_impressions_map", sq5Var3);
        FEATURE_FLAGS_IMPRESSIONS_MAP = fq5Var8;
        fq5 fq5Var9 = new fq5("CONTENT_CARDS", 8, "content_cards", sq5Var);
        CONTENT_CARDS = fq5Var9;
        fq5 fq5Var10 = new fq5("DISMISSED_CARDS", 9, MetricTracker.Action.DISMISSED, sq5Var);
        DISMISSED_CARDS = fq5Var10;
        fq5 fq5Var11 = new fq5("EXPIRED_CARDS", 10, "expired", sq5Var);
        EXPIRED_CARDS = fq5Var11;
        fq5 fq5Var12 = new fq5("TEST_CARDS", 11, "test", sq5Var);
        TEST_CARDS = fq5Var12;
        fq5 fq5Var13 = new fq5("LAST_CARD_UPDATED_AT", 12, "last_card_updated_at", sq5Var2);
        LAST_CARD_UPDATED_AT = fq5Var13;
        fq5 fq5Var14 = new fq5("LAST_FULL_CARD_SYNC_AT", 13, "last_full_sync_at", sq5Var2);
        LAST_FULL_CARD_SYNC_AT = fq5Var14;
        fq5 fq5Var15 = new fq5("LAST_CARD_STORAGE_UPDATE_TIMESTAMP", 14, "last_storage_update_timestamp", sq5Var2);
        LAST_CARD_STORAGE_UPDATE_TIMESTAMP = fq5Var15;
        sq5 sq5Var4 = sq5.STRING;
        fq5 fq5Var16 = new fq5("LAST_ACCESSED_SDK_VERSION", 15, "last_accessed_sdk_version", sq5Var4);
        LAST_ACCESSED_SDK_VERSION = fq5Var16;
        fq5 fq5Var17 = new fq5("TRIGGERED_ACTIONS", 16, "triggers", sq5Var);
        TRIGGERED_ACTIONS = fq5Var17;
        fq5 fq5Var18 = new fq5("TRIGGERED_ACTIONS_IMPRESSION_MAP", 17, "triggers_impression_map", sq5Var3);
        TRIGGERED_ACTIONS_IMPRESSION_MAP = fq5Var18;
        fq5 fq5Var19 = new fq5("TRIGGERS_CHECKSUM", 18, "triggers_checksum", sq5Var4);
        TRIGGERS_CHECKSUM = fq5Var19;
        fq5 fq5Var20 = new fq5("BANNERS", 19, "banners", sq5Var);
        BANNERS = fq5Var20;
        fq5 fq5Var21 = new fq5("BANNERS_IMPRESSION_MAP", 20, "banners_impression_map", sq5Var3);
        BANNERS_IMPRESSION_MAP = fq5Var21;
        fq5 fq5Var22 = new fq5("BANNERS_PENDING_DISMISSALS", 21, "banners_pending_dismissals", sq5Var);
        BANNERS_PENDING_DISMISSALS = fq5Var22;
        fq5 fq5Var23 = new fq5("BANNERS_LAST_REQUEST_TIME_PER_PLACEMENT", 22, "banners_last_request_time_per_placement", sq5Var3);
        BANNERS_LAST_REQUEST_TIME_PER_PLACEMENT = fq5Var23;
        fq5 fq5Var24 = new fq5("MITE_KEY", 23, "mite", sq5Var4);
        MITE_KEY = fq5Var24;
        fq5 fq5Var25 = new fq5("DUST_HOST", 24, "dust_host", sq5Var4);
        DUST_HOST = fq5Var25;
        fq5 fq5Var26 = new fq5("DUST_AUTH", 25, "dust_auth", sq5Var4);
        DUST_AUTH = fq5Var26;
        fq5 fq5Var27 = new fq5("DUST_RCS", 26, "dust_rcs", sq5Var4);
        DUST_RCS = fq5Var27;
        fq5 fq5Var28 = new fq5("DUST_AUTH_EXPIRATION_SECONDS", 27, "dust_auth_expiration_seconds", sq5Var2);
        DUST_AUTH_EXPIRATION_SECONDS = fq5Var28;
        fq5 fq5Var29 = new fq5("SDK_METADATA", 28, "tags", sq5Var);
        SDK_METADATA = fq5Var29;
        fq5 fq5Var30 = new fq5("PUSH_MAX_LAST_UPDATE", 29, "lastUpdateTime", sq5Var2);
        PUSH_MAX_LAST_UPDATE = fq5Var30;
        fq5 fq5Var31 = new fq5("PUSH_MAX_CAMPAIGNS", 30, "push_max_campaigns", sq5Var3);
        PUSH_MAX_CAMPAIGNS = fq5Var31;
        fq5 fq5Var32 = new fq5("PUSH_DELIVERY_EVENTS", 31, "push_delivery_events", sq5Var3);
        PUSH_DELIVERY_EVENTS = fq5Var32;
        fq5 fq5Var33 = new fq5("SDK_AUTH", 32, "auth_signature", sq5Var4);
        SDK_AUTH = fq5Var33;
        sq5 sq5Var5 = sq5.BOOLEAN;
        fq5 fq5Var34 = new fq5("SDK_ENABLEMENT", 33, "appboy_sdk_disabled", sq5Var5);
        SDK_ENABLEMENT = fq5Var34;
        fq5 fq5Var35 = new fq5("CONFIG_TIME", 34, "config_time", sq5Var2);
        CONFIG_TIME = fq5Var35;
        fq5 fq5Var36 = new fq5("EPHEMERAL_EVENTS_ENABLED", 35, "ephemeral_events_enabled", sq5Var5);
        EPHEMERAL_EVENTS_ENABLED = fq5Var36;
        fq5 fq5Var37 = new fq5("GEOFENCES_ENABLED_SET", 36, "geofences_enabled_set", sq5Var5);
        GEOFENCES_ENABLED_SET = fq5Var37;
        fq5 fq5Var38 = new fq5("GEOFENCES_ENABLED", 37, "geofences_enabled", sq5Var5);
        GEOFENCES_ENABLED = fq5Var38;
        sq5 sq5Var6 = sq5.INT;
        fq5 fq5Var39 = new fq5("GEOFENCES_MIN_TIME_REQUEST", 38, "geofences_min_time_since_last_request", sq5Var6);
        GEOFENCES_MIN_TIME_REQUEST = fq5Var39;
        fq5 fq5Var40 = new fq5("GEOFENCES_MIN_TIME_REPORT", 39, "geofences_min_time_since_last_report", sq5Var6);
        GEOFENCES_MIN_TIME_REPORT = fq5Var40;
        fq5 fq5Var41 = new fq5("GEOFENCES_MAX_NUM_TO_REGISTER", 40, "geofences_max_num_to_register", sq5Var6);
        GEOFENCES_MAX_NUM_TO_REGISTER = fq5Var41;
        fq5 fq5Var42 = new fq5("MESSAGING_SESSION_TIMEOUT", 41, "messaging_session_timeout", sq5Var2);
        MESSAGING_SESSION_TIMEOUT = fq5Var42;
        fq5 fq5Var43 = new fq5("MINIMUM_SESSION_TIMEOUT", 42, "minimum_session_timeout", sq5Var6);
        MINIMUM_SESSION_TIMEOUT = fq5Var43;
        fq5 fq5Var44 = new fq5("DUST_ENABLED", 43, "dust_enabled", sq5Var5);
        DUST_ENABLED = fq5Var44;
        fq5 fq5Var45 = new fq5("DUST_SHOULD_BLOCK_CC_REFRESH", 44, "dust_should_block_cc_refresh", sq5Var5);
        DUST_SHOULD_BLOCK_CC_REFRESH = fq5Var45;
        fq5 fq5Var46 = new fq5("BLOCKLISTED_EVENTS", 45, "blacklisted_events", sq5Var);
        BLOCKLISTED_EVENTS = fq5Var46;
        fq5 fq5Var47 = new fq5("BLOCKLISTED_ATTRIBUTES", 46, "blacklisted_attributes", sq5Var);
        BLOCKLISTED_ATTRIBUTES = fq5Var47;
        fq5 fq5Var48 = new fq5("BLOCKLISTED_PURCHASES", 47, "blacklisted_purchases", sq5Var);
        BLOCKLISTED_PURCHASES = fq5Var48;
        fq5 fq5Var49 = new fq5("CONTENT_CARDS_ENABLED", 48, "content_cards_enabled", sq5Var5);
        CONTENT_CARDS_ENABLED = fq5Var49;
        fq5 fq5Var50 = new fq5("FEATURE_FLAGS_ENABLED", 49, "feature_flags_enabled", sq5Var5);
        FEATURE_FLAGS_ENABLED = fq5Var50;
        fq5 fq5Var51 = new fq5("FEATURE_FLAGS_RATE_REFRESH_RATE_LIMIT", 50, "feature_flags_refresh_rate_limit", sq5Var6);
        FEATURE_FLAGS_RATE_REFRESH_RATE_LIMIT = fq5Var51;
        fq5 fq5Var52 = new fq5("PUSH_MAX_ENABLED", 51, "push_max_enabled", sq5Var5);
        PUSH_MAX_ENABLED = fq5Var52;
        fq5 fq5Var53 = new fq5("PUSH_MAX_REDELIVER_BUFFER", 52, "push_max_redeliver_buffer", sq5Var2);
        PUSH_MAX_REDELIVER_BUFFER = fq5Var53;
        fq5 fq5Var54 = new fq5("PUSH_MAX_REDELIVER_DEDUPE_BUFFER", 53, "push_max_redeliver_dedupe_buffer", sq5Var2);
        PUSH_MAX_REDELIVER_DEDUPE_BUFFER = fq5Var54;
        fq5 fq5Var55 = new fq5("GLOBAL_REQUEST_RATE_LIMITING_ENABLED", 54, "global_req_rate_limit_enabled", sq5Var5);
        GLOBAL_REQUEST_RATE_LIMITING_ENABLED = fq5Var55;
        fq5 fq5Var56 = new fq5("GLOBAL_REQUEST_RATE_LIMITING_CAPACITY", 55, "global_req_rate_capacity", sq5Var6);
        GLOBAL_REQUEST_RATE_LIMITING_CAPACITY = fq5Var56;
        fq5 fq5Var57 = new fq5("GLOBAL_REQUEST_RATE_LIMITING_REFILL_RATE", 56, "global_req_rate_refill_rate", sq5Var6);
        GLOBAL_REQUEST_RATE_LIMITING_REFILL_RATE = fq5Var57;
        fq5 fq5Var58 = new fq5("GLOBAL_REQUEST_RATE_LIMIT_ENDPOINT_OVERRIDES", 57, "global_req_rate_limit_endpoint_overrides", sq5Var4);
        GLOBAL_REQUEST_RATE_LIMIT_ENDPOINT_OVERRIDES = fq5Var58;
        fq5 fq5Var59 = new fq5("DEFAULT_REQUEST_BACKOFF_MIN_SLEEP_DURATION_MS", 58, "default_backoff_min_sleep_duration__ms", sq5Var6);
        DEFAULT_REQUEST_BACKOFF_MIN_SLEEP_DURATION_MS = fq5Var59;
        fq5 fq5Var60 = new fq5("DEFAULT_REQUEST_BACKOFF_MAX_SLEEP_DURATION_MS", 59, "default_backoff_max_sleep_duration_ms", sq5Var6);
        DEFAULT_REQUEST_BACKOFF_MAX_SLEEP_DURATION_MS = fq5Var60;
        fq5 fq5Var61 = new fq5("DEFAULT_REQUEST_BACKOFF_SCALE_FACTOR", 60, "default_backoff_scale_factor", sq5Var6);
        DEFAULT_REQUEST_BACKOFF_SCALE_FACTOR = fq5Var61;
        fq5 fq5Var62 = new fq5("SDK_DEBUGGER_ENABLED", 61, "sdk_debugger_enabled", sq5Var5);
        SDK_DEBUGGER_ENABLED = fq5Var62;
        fq5 fq5Var63 = new fq5("SDK_DEBUGGER_EXPIRATION_TIME", 62, "sdk_debugger_expiration_time", sq5Var2);
        SDK_DEBUGGER_EXPIRATION_TIME = fq5Var63;
        fq5 fq5Var64 = new fq5("SDK_DEBUGGER_AUTHORIZATION_CODE", 63, "sdk_debugger_authorization_code", sq5Var4);
        SDK_DEBUGGER_AUTHORIZATION_CODE = fq5Var64;
        fq5 fq5Var65 = new fq5("SDK_DEBUGGER_FLUSH_INTERVAL_BYTES", 64, "sdk_debugger_flush_interval_bytes", sq5Var2);
        SDK_DEBUGGER_FLUSH_INTERVAL_BYTES = fq5Var65;
        fq5 fq5Var66 = new fq5("SDK_DEBUGGER_FLUSH_INTERVAL_SECONDS", 65, "sdk_debugger_flush_interval_seconds", sq5Var2);
        SDK_DEBUGGER_FLUSH_INTERVAL_SECONDS = fq5Var66;
        fq5 fq5Var67 = new fq5("SDK_DEBUGGER_MAX_PAYLOAD_BYTES", 66, "sdk_debugger_max_payload_bytes", sq5Var2);
        SDK_DEBUGGER_MAX_PAYLOAD_BYTES = fq5Var67;
        fq5 fq5Var68 = new fq5("BANNERS_ENABLED", 67, "banners_enabled", sq5Var5);
        BANNERS_ENABLED = fq5Var68;
        fq5 fq5Var69 = new fq5("MAX_BANNER_PLACEMENTS", 68, "max_banner_placements", sq5Var6);
        MAX_BANNER_PLACEMENTS = fq5Var69;
        fq5 fq5Var70 = new fq5("BANNERS_DISMISSALS_CACHE_SIZE", 69, "banners_dismissals_cache_size", sq5Var6);
        BANNERS_DISMISSALS_CACHE_SIZE = fq5Var70;
        fq5 fq5Var71 = new fq5("PUSH_REGISTRATION_VERSION_CODE", 70, "version_code", sq5Var6);
        PUSH_REGISTRATION_VERSION_CODE = fq5Var71;
        fq5 fq5Var72 = new fq5("PUSH_REGISTRATION_PERSISTENT_DEVICE_ID", 71, "device_identifier", sq5Var4);
        PUSH_REGISTRATION_PERSISTENT_DEVICE_ID = fq5Var72;
        fq5 fq5Var73 = new fq5("PUSH_REGISTRATION_ID_KEY", 72, "registration_id", sq5Var4);
        PUSH_REGISTRATION_ID_KEY = fq5Var73;
        fq5 fq5Var74 = new fq5("CURRENT_OPEN_SESSION_ID", 73, "current_open_session", sq5Var4);
        CURRENT_OPEN_SESSION_ID = fq5Var74;
        fq5 fq5Var75 = new fq5("SESSION_STORAGE_MAP", 74, "session_storage_map", sq5Var3);
        SESSION_STORAGE_MAP = fq5Var75;
        fq5 fq5Var76 = new fq5("DELAYED_INIT_ENABLED", 75, "delayed_initialization_enabled", sq5Var5);
        DELAYED_INIT_ENABLED = fq5Var76;
        fq5 fq5Var77 = new fq5("DELAYED_INIT_SET_DURING_RUNTIME_FLAG", 76, "was_set_during_runtime", sq5Var5);
        DELAYED_INIT_SET_DURING_RUNTIME_FLAG = fq5Var77;
        fq5 fq5Var78 = new fq5("DELAYED_INIT_ANALYTICS_BEHAVIOR_FLAG", 77, "analytics_behavior", sq5Var4);
        DELAYED_INIT_ANALYTICS_BEHAVIOR_FLAG = fq5Var78;
        fq5 fq5Var79 = new fq5("MESSAGING_SESSION_END_TIMESTAMP", 78, "messaging_session_timestamp", sq5Var2);
        MESSAGING_SESSION_END_TIMESTAMP = fq5Var79;
        fq5 fq5Var80 = new fq5("EVENT_STORAGE_MAP", 79, RadarTrackingOptions.RadarTrackingOptionsSync.EVENTS_STR, sq5Var3);
        EVENT_STORAGE_MAP = fq5Var80;
        fq5 fq5Var81 = new fq5("PUSH_ID_MAP", 80, "push_id_map", sq5Var3);
        PUSH_ID_MAP = fq5Var81;
        fq5 fq5Var82 = new fq5("SERIALIZED_USER_OBJECT", 81, "user_cache_attributes_object", sq5Var4);
        SERIALIZED_USER_OBJECT = fq5Var82;
        fq5 fq5Var83 = new fq5("PUSH_TOKEN", 82, "push_token", sq5Var4);
        PUSH_TOKEN = fq5Var83;
        fq5 fq5Var84 = new fq5("EVENT_DUPLICATION_VALIDATION_STORAGE_MAP", 83, "event_duplication_validation_storage_map", sq5Var3);
        EVENT_DUPLICATION_VALIDATION_STORAGE_MAP = fq5Var84;
        fq5 fq5Var85 = new fq5("API_KEY", 84, "com_braze_api_key", sq5Var4);
        API_KEY = fq5Var85;
        fq5 fq5Var86 = new fq5("SERVER_TARGET", 85, "com_braze_server_target", sq5Var4);
        SERVER_TARGET = fq5Var86;
        fq5 fq5Var87 = new fq5("SDK_FLAVOR", 86, "com_braze_sdk_flavor", sq5Var4);
        SDK_FLAVOR = fq5Var87;
        fq5 fq5Var88 = new fq5("CUSTOM_ENDPOINT", 87, "com_braze_custom_endpoint", sq5Var4);
        CUSTOM_ENDPOINT = fq5Var88;
        fq5 fq5Var89 = new fq5("SMALL_NOTIFICATION_ICON", 88, "com_braze_push_small_notification_icon", sq5Var4);
        SMALL_NOTIFICATION_ICON = fq5Var89;
        fq5 fq5Var90 = new fq5("LARGE_NOTIFICATION_ICON", 89, "com_braze_push_large_notification_icon", sq5Var4);
        LARGE_NOTIFICATION_ICON = fq5Var90;
        fq5 fq5Var91 = new fq5("SESSION_TIMEOUT", 90, "com_braze_session_timeout", sq5Var6);
        SESSION_TIMEOUT = fq5Var91;
        fq5 fq5Var92 = new fq5("DEFAULT_NOTIFICATION_ACCENT_COLOR", 91, "com_braze_default_notification_accent_color", sq5Var6);
        DEFAULT_NOTIFICATION_ACCENT_COLOR = fq5Var92;
        fq5 fq5Var93 = new fq5("TRIGGER_ACTION_MINIMUM_TIME_INTERVAL_SECONDS", 92, "com_braze_trigger_action_minimum_time_interval_seconds", sq5Var6);
        TRIGGER_ACTION_MINIMUM_TIME_INTERVAL_SECONDS = fq5Var93;
        fq5 fq5Var94 = new fq5("ADM_MESSAGING_REGISTRATION_ENABLED", 93, "com_braze_push_adm_messaging_registration_enabled", sq5Var5);
        ADM_MESSAGING_REGISTRATION_ENABLED = fq5Var94;
        fq5 fq5Var95 = new fq5("HANDLE_PUSH_DEEP_LINKS_AUTOMATICALLY", 94, "com_braze_handle_push_deep_links_automatically", sq5Var5);
        HANDLE_PUSH_DEEP_LINKS_AUTOMATICALLY = fq5Var95;
        fq5 fq5Var96 = new fq5("AUTOMATIC_LOCATION_COLLECTION", 95, "com_braze_enable_location_collection", sq5Var5);
        AUTOMATIC_LOCATION_COLLECTION = fq5Var96;
        fq5 fq5Var97 = new fq5("DATA_SYNC_BAD_NETWORK_INTERVAL", 96, "com_braze_data_flush_interval_bad_network", sq5Var6);
        DATA_SYNC_BAD_NETWORK_INTERVAL = fq5Var97;
        fq5 fq5Var98 = new fq5("DATA_SYNC_GOOD_NETWORK_INTERVAL", 97, "com_braze_data_flush_interval_good_network", sq5Var6);
        DATA_SYNC_GOOD_NETWORK_INTERVAL = fq5Var98;
        fq5 fq5Var99 = new fq5("DATA_SYNC_GREAT_NETWORK_INTERVAL", 98, "com_braze_data_flush_interval_great_network", sq5Var6);
        DATA_SYNC_GREAT_NETWORK_INTERVAL = fq5Var99;
        fq5 fq5Var100 = new fq5("DEFAULT_NOTIFICATION_CHANNEL_NAME", 99, "com_braze_default_notification_channel_name", sq5Var4);
        DEFAULT_NOTIFICATION_CHANNEL_NAME = fq5Var100;
        fq5 fq5Var101 = new fq5("DEFAULT_NOTIFICATION_CHANNEL_DESCRIPTION", 100, "com_braze_default_notification_channel_description", sq5Var4);
        DEFAULT_NOTIFICATION_CHANNEL_DESCRIPTION = fq5Var101;
        fq5 fq5Var102 = new fq5("PUSH_DEEP_LINK_BACK_STACK_ACTIVITY_ENABLED", 101, "com_braze_push_deep_link_back_stack_activity_enabled", sq5Var5);
        PUSH_DEEP_LINK_BACK_STACK_ACTIVITY_ENABLED = fq5Var102;
        fq5 fq5Var103 = new fq5("PUSH_DEEP_LINK_BACK_STACK_ACTIVITY_CLASS_NAME", 102, "com_braze_push_deep_link_back_stack_activity_class_name", sq5Var4);
        PUSH_DEEP_LINK_BACK_STACK_ACTIVITY_CLASS_NAME = fq5Var103;
        fq5 fq5Var104 = new fq5("SESSION_START_BASED_TIMEOUT_ENABLED", HttpStatusCodesKt.HTTP_EARLY_HINTS, "com_braze_session_start_based_timeout_enabled", sq5Var5);
        SESSION_START_BASED_TIMEOUT_ENABLED = fq5Var104;
        fq5 fq5Var105 = new fq5("FIREBASE_CLOUD_MESSAGING_REGISTRATION_ENABLED", 104, "com_braze_firebase_cloud_messaging_registration_enabled", sq5Var5);
        FIREBASE_CLOUD_MESSAGING_REGISTRATION_ENABLED = fq5Var105;
        fq5 fq5Var106 = new fq5("FIREBASE_CLOUD_MESSAGING_SENDER_ID", 105, "com_braze_firebase_cloud_messaging_sender_id", sq5Var4);
        FIREBASE_CLOUD_MESSAGING_SENDER_ID = fq5Var106;
        fq5 fq5Var107 = new fq5("CONTENT_CARDS_UNREAD_VISUAL_INDICATOR_ENABLED", 106, "com_braze_content_cards_unread_visual_indicator_enabled", sq5Var5);
        CONTENT_CARDS_UNREAD_VISUAL_INDICATOR_ENABLED = fq5Var107;
        fq5 fq5Var108 = new fq5("DEVICE_OBJECT_ALLOWLISTING_ENABLED", 107, "com_braze_device_object_whitelisting_enabled", sq5Var5);
        DEVICE_OBJECT_ALLOWLISTING_ENABLED = fq5Var108;
        fq5 fq5Var109 = new fq5("IN_APP_MESSAGE_ACCESSIBILITY_EXCLUSIVE_MODE_ENABLED", 108, "com_braze_device_in_app_message_accessibility_exclusive_mode_enabled", sq5Var5);
        IN_APP_MESSAGE_ACCESSIBILITY_EXCLUSIVE_MODE_ENABLED = fq5Var109;
        fq5 fq5Var110 = new fq5("PUSH_WAKE_SCREEN_FOR_NOTIFICATION_ENABLED", 109, "com_braze_push_wake_screen_for_notification_enabled", sq5Var5);
        PUSH_WAKE_SCREEN_FOR_NOTIFICATION_ENABLED = fq5Var110;
        fq5 fq5Var111 = new fq5("PUSH_NOTIFICATION_HTML_RENDERING_ENABLED", 110, "com_braze_push_notification_html_rendering_enabled", sq5Var5);
        PUSH_NOTIFICATION_HTML_RENDERING_ENABLED = fq5Var111;
        fq5 fq5Var112 = new fq5("DOES_PUSH_STORY_DISMISS_ON_CLICK", 111, "com_braze_does_push_story_dismiss_on_click", sq5Var5);
        DOES_PUSH_STORY_DISMISS_ON_CLICK = fq5Var112;
        fq5 fq5Var113 = new fq5("GEOFENCES_ENABLED_CONFIG", 112, "com_braze_geofences_enabled", sq5Var5);
        GEOFENCES_ENABLED_CONFIG = fq5Var113;
        fq5 fq5Var114 = new fq5("IN_APP_MESSAGE_PUSH_TEST_EAGER_DISPLAY", 113, "com_braze_in_app_message_push_test_eager_display_enabled", sq5Var5);
        IN_APP_MESSAGE_PUSH_TEST_EAGER_DISPLAY = fq5Var114;
        fq5 fq5Var115 = new fq5("CUSTOM_HTML_WEBVIEW_ACTIVITY_CLASS_NAME", 114, "com_braze_custom_html_webview_activity_class_name", sq5Var4);
        CUSTOM_HTML_WEBVIEW_ACTIVITY_CLASS_NAME = fq5Var115;
        fq5 fq5Var116 = new fq5("GEOFENCES_AUTOMATIC_REQUESTS_ENABLED", 115, "com_braze_automatic_geofence_requests_enabled", sq5Var5);
        GEOFENCES_AUTOMATIC_REQUESTS_ENABLED = fq5Var116;
        fq5 fq5Var117 = new fq5("IN_APP_MESSAGE_WEBVIEW_CLIENT_MAX_ONPAGEFINISHED_WAIT", 116, "com_braze_in_app_message_webview_client_max_onpagefinished_wait_ms", sq5Var6);
        IN_APP_MESSAGE_WEBVIEW_CLIENT_MAX_ONPAGEFINISHED_WAIT = fq5Var117;
        fq5 fq5Var118 = new fq5("FIREBASE_MESSAGING_SERVICE_AUTOMATICALLY_REGISTER_ON_NEW_TOKEN", 117, "com_braze_firebase_messaging_service_automatically_register_on_new_token", sq5Var5);
        FIREBASE_MESSAGING_SERVICE_AUTOMATICALLY_REGISTER_ON_NEW_TOKEN = fq5Var118;
        fq5 fq5Var119 = new fq5("SDK_AUTH_ENABLED", 118, "com_braze_sdk_authentication_enabled", sq5Var5);
        SDK_AUTH_ENABLED = fq5Var119;
        fq5 fq5Var120 = new fq5("REQUIRE_TOUCH_MODE_FOR_HTML_IAMS", 119, "com_braze_require_touch_mode_for_html_in_app_messages", sq5Var5);
        REQUIRE_TOUCH_MODE_FOR_HTML_IAMS = fq5Var120;
        fq5 fq5Var121 = new fq5("HTML_IN_APP_MESSAGE_APPLY_WINDOW_INSETS", 120, "com_braze_html_in_app_message_apply_insets", sq5Var5);
        HTML_IN_APP_MESSAGE_APPLY_WINDOW_INSETS = fq5Var121;
        fq5 fq5Var122 = new fq5("HTML_IN_APP_MESSAGE_ENABLE_HTML_LINK_TARGET", 121, "com_braze_html_in_app_message_enable_html_link_target", sq5Var5);
        HTML_IN_APP_MESSAGE_ENABLE_HTML_LINK_TARGET = fq5Var122;
        fq5 fq5Var123 = new fq5("DEVICE_OBJECT_ALLOWLIST", 122, "com_braze_device_object_whitelist", sq5Var);
        DEVICE_OBJECT_ALLOWLIST = fq5Var123;
        fq5 fq5Var124 = new fq5("CUSTOM_LOCATION_PROVIDERS_LIST", 123, "com_braze_custom_location_providers_list", sq5Var);
        CUSTOM_LOCATION_PROVIDERS_LIST = fq5Var124;
        fq5 fq5Var125 = new fq5("SDK_METADATA_CONFIG", 124, "com_braze_sdk_metadata", sq5Var);
        SDK_METADATA_CONFIG = fq5Var125;
        fq5 fq5Var126 = new fq5("FALLBACK_FCM_SERVICE_ENABLED", 125, "com_braze_fallback_firebase_cloud_messaging_service_enabled", sq5Var5);
        FALLBACK_FCM_SERVICE_ENABLED = fq5Var126;
        fq5 fq5Var127 = new fq5("FALLBACK_FCM_SERVICE_CLASSPATH", WebSocketProtocol.PAYLOAD_SHORT, "com_braze_fallback_firebase_cloud_messaging_service_classpath", sq5Var4);
        FALLBACK_FCM_SERVICE_CLASSPATH = fq5Var127;
        fq5 fq5Var128 = new fq5("OPTIN_WHEN_PUSH_AUTHORIZED", 127, "com_braze_optin_when_push_authorized", sq5Var5);
        OPTIN_WHEN_PUSH_AUTHORIZED = fq5Var128;
        fq5 fq5Var129 = new fq5("USE_WINDOW_FLAG_SECURE_IN_ACTIVITIES", 128, "com_braze_use_activity_window_flag_secure", sq5Var5);
        USE_WINDOW_FLAG_SECURE_IN_ACTIVITIES = fq5Var129;
        fq5 fq5Var130 = new fq5("PERSIST_IAM_WEBVIEW_WHEN_BACKGROUNDING_APP", 129, "com_braze_persist_webview_when_backgrounding_app", sq5Var5);
        PERSIST_IAM_WEBVIEW_WHEN_BACKGROUNDING_APP = fq5Var130;
        fq5 fq5Var131 = new fq5("IN_APP_MESSAGE_ADD_STATUS_BAR_PADDING", 130, "com_braze_in_app_message_add_status_bar_padding", sq5Var5);
        IN_APP_MESSAGE_ADD_STATUS_BAR_PADDING = fq5Var131;
        fq5 fq5Var132 = new fq5("INAPP_LISTENER_GAME_OBJECT_NAME", 131, "com_braze_inapp_listener_game_object_name", sq5Var4);
        INAPP_LISTENER_GAME_OBJECT_NAME = fq5Var132;
        fq5 fq5Var133 = new fq5("INAPP_LISTENER_CALLBACK_METHOD_NAME", 132, "com_braze_inapp_listener_callback_method_name", sq5Var4);
        INAPP_LISTENER_CALLBACK_METHOD_NAME = fq5Var133;
        fq5 fq5Var134 = new fq5("INAPP_SHOW_INAPP_MESSAGES_AUTOMATICALLY", 133, "com_braze_inapp_show_inapp_messages_automatically", sq5Var5);
        INAPP_SHOW_INAPP_MESSAGES_AUTOMATICALLY = fq5Var134;
        fq5 fq5Var135 = new fq5("PUSH_RECEIVED_GAME_OBJECT_NAME", 134, "com_braze_push_received_game_object_name", sq5Var4);
        PUSH_RECEIVED_GAME_OBJECT_NAME = fq5Var135;
        fq5 fq5Var136 = new fq5("PUSH_RECEIVED_CALLBACK_METHOD_NAME", 135, "com_braze_push_received_callback_method_name", sq5Var4);
        PUSH_RECEIVED_CALLBACK_METHOD_NAME = fq5Var136;
        fq5 fq5Var137 = new fq5("PUSH_OPENED_GAME_OBJECT_NAME", 136, "com_braze_push_opened_game_object_name", sq5Var4);
        PUSH_OPENED_GAME_OBJECT_NAME = fq5Var137;
        fq5 fq5Var138 = new fq5("PUSH_OPENED_CALLBACK_METHOD_NAME", 137, "com_braze_push_opened_callback_method_name", sq5Var4);
        PUSH_OPENED_CALLBACK_METHOD_NAME = fq5Var138;
        fq5 fq5Var139 = new fq5("PUSH_DELETED_GAME_OBJECT_NAME", 138, "com_braze_push_deleted_game_object_name", sq5Var4);
        PUSH_DELETED_GAME_OBJECT_NAME = fq5Var139;
        fq5 fq5Var140 = new fq5("PUSH_DELETED_CALLBACK_METHOD_NAME", 139, "com_braze_push_deleted_callback_method_name", sq5Var4);
        PUSH_DELETED_CALLBACK_METHOD_NAME = fq5Var140;
        fq5 fq5Var141 = new fq5("CONTENT_CARDS_UPDATED_LISTENER_GAME_OBJECT_NAME", 140, "com_braze_content_cards_updated_listener_game_object_name", sq5Var4);
        CONTENT_CARDS_UPDATED_LISTENER_GAME_OBJECT_NAME = fq5Var141;
        fq5 fq5Var142 = new fq5("CONTENT_CARDS_UPDATED_LISTENER_CALLBACK_METHOD_NAME", 141, "com_braze_content_cards_updated_listener_callback_method_name", sq5Var4);
        CONTENT_CARDS_UPDATED_LISTENER_CALLBACK_METHOD_NAME = fq5Var142;
        fq5 fq5Var143 = new fq5("FEATURE_FLAGS_UPDATED_LISTENER_GAME_OBJECT_NAME", 142, "com_braze_feature_flags_updated_listener_game_object_name", sq5Var4);
        FEATURE_FLAGS_UPDATED_LISTENER_GAME_OBJECT_NAME = fq5Var143;
        fq5 fq5Var144 = new fq5("FEATURE_FLAGS_UPDATED_LISTENER_CALLBACK_METHOD_NAME", 143, "com_braze_feature_flags_updated_listener_callback_method_name", sq5Var4);
        FEATURE_FLAGS_UPDATED_LISTENER_CALLBACK_METHOD_NAME = fq5Var144;
        fq5 fq5Var145 = new fq5("SDK_AUTHENTICATION_FAILURE_LISTENER_GAME_OBJECT_NAME", 144, "com_braze_sdk_authentication_failure_listener_game_object_name", sq5Var4);
        SDK_AUTHENTICATION_FAILURE_LISTENER_GAME_OBJECT_NAME = fq5Var145;
        fq5 fq5Var146 = new fq5("SDK_AUTHENTICATION_FAILURE_LISTENER_CALLBACK_METHOD_NAME", 145, "com_braze_sdk_authentication_failure_listener_callback_method_name", sq5Var4);
        SDK_AUTHENTICATION_FAILURE_LISTENER_CALLBACK_METHOD_NAME = fq5Var146;
        fq5 fq5Var147 = new fq5("INAPP_AUTO_SET_MANAGER_LISTENER", 146, "com_braze_inapp_auto_set_manager_listener_key", sq5Var5);
        INAPP_AUTO_SET_MANAGER_LISTENER = fq5Var147;
        fq5 fq5Var148 = new fq5("INAPP_INITIAL_DISPLAY_OPERATION", 147, "com_braze_inapp_initial_display_operation_key", sq5Var4);
        INAPP_INITIAL_DISPLAY_OPERATION = fq5Var148;
        fq5 fq5Var149 = new fq5("LAST_USER_ID", 148, "last_user", sq5Var4);
        LAST_USER_ID = fq5Var149;
        fq5 fq5Var150 = new fq5("SUFFIX_CACHE_USER_ID_HASH", 149, "user_id_hash_value", sq5Var4);
        SUFFIX_CACHE_USER_ID_HASH = fq5Var150;
        fq5 fq5Var151 = new fq5("SUFFIX_CACHE_USER_ID_KEY", 150, "user_id_key", sq5Var4);
        SUFFIX_CACHE_USER_ID_KEY = fq5Var151;
        fq5 fq5Var152 = new fq5("DEVICE_ID", 151, "device_id", sq5Var4);
        DEVICE_ID = fq5Var152;
        fq5 fq5Var153 = new fq5("LEGACY_DEVICE_ID", 152, "legacy_device_id", sq5Var4);
        LEGACY_DEVICE_ID = fq5Var153;
        fq5 fq5Var154 = new fq5("PERSISTENT_DEVICE_ID", 153, "persistent_device_id", sq5Var4);
        PERSISTENT_DEVICE_ID = fq5Var154;
        fq5 fq5Var155 = new fq5("CACHED_DEVICE", 154, "cached_device", sq5Var4);
        CACHED_DEVICE = fq5Var155;
        fq5 fq5Var156 = new fq5("DEVICE_CACHE_SEND_FULL_ON_NEXT_EXPORT", 155, "sfone", sq5Var5);
        DEVICE_CACHE_SEND_FULL_ON_NEXT_EXPORT = fq5Var156;
        fq5 fq5Var157 = new fq5("DEVICE_CACHE_LAST_OS_VERSION", 156, "ldov", sq5Var6);
        DEVICE_CACHE_LAST_OS_VERSION = fq5Var157;
        fq5 fq5Var158 = new fq5("PERMISSION_REQUEST_COUNTS", 157, "permission_request_counts", sq5Var3);
        PERMISSION_REQUEST_COUNTS = fq5Var158;
        fq5 fq5Var159 = new fq5("GOOGLE_ADVERTISING_ID", 158, "google_ad_id", sq5Var4);
        GOOGLE_ADVERTISING_ID = fq5Var159;
        fq5 fq5Var160 = new fq5("AD_TRACKING_ENABLED", 159, "ad_tracking_enabled", sq5Var5);
        AD_TRACKING_ENABLED = fq5Var160;
        fq5 fq5Var161 = new fq5("ENDPOINT_LAST_REQUEST_MAP", 160, "endpoint_last_request_map", sq5Var3);
        ENDPOINT_LAST_REQUEST_MAP = fq5Var161;
        fq5 fq5Var162 = new fq5("ENDPOINT_ATTEMPT_COUNT_MAP", 161, "endpoint_attempt_count_map", sq5Var3);
        ENDPOINT_ATTEMPT_COUNT_MAP = fq5Var162;
        sq5 sq5Var7 = sq5.FLOAT;
        fq5 fq5Var163 = new fq5("TOKEN_BUCKET_CURRENT_TOKEN_COUNT", 162, "current_token_count", sq5Var7);
        TOKEN_BUCKET_CURRENT_TOKEN_COUNT = fq5Var163;
        fq5 fq5Var164 = new fq5("TOKEN_BUCKET_LAST_CALL_AT_MS", 163, "last_call_at_ms", sq5Var2);
        TOKEN_BUCKET_LAST_CALL_AT_MS = fq5Var164;
        fq5 fq5Var165 = new fq5("TEST_STRING_KEY", 164, "string_key", sq5Var4);
        TEST_STRING_KEY = fq5Var165;
        fq5 fq5Var166 = new fq5("TEST_STRING_KEY_2", 165, "string_key_2", sq5Var4);
        TEST_STRING_KEY_2 = fq5Var166;
        fq5 fq5Var167 = new fq5("TEST_LONG_KEY", 166, "long_key", sq5Var2);
        TEST_LONG_KEY = fq5Var167;
        fq5 fq5Var168 = new fq5("TEST_LONG_KEY_2", 167, "long_key_2", sq5Var2);
        TEST_LONG_KEY_2 = fq5Var168;
        fq5 fq5Var169 = new fq5("TEST_INT_KEY", 168, "int_key", sq5Var6);
        TEST_INT_KEY = fq5Var169;
        fq5 fq5Var170 = new fq5("TEST_INT_KEY_2", 169, "int_key_2", sq5Var6);
        TEST_INT_KEY_2 = fq5Var170;
        fq5 fq5Var171 = new fq5("TEST_DOUBLE_KEY", 170, "double_key", sq5.DOUBLE);
        TEST_DOUBLE_KEY = fq5Var171;
        fq5 fq5Var172 = new fq5("TEST_FLOAT_KEY", 171, "float_key", sq5Var7);
        TEST_FLOAT_KEY = fq5Var172;
        fq5 fq5Var173 = new fq5("TEST_FLOAT_KEY_2", 172, "float_key_2", sq5Var7);
        TEST_FLOAT_KEY_2 = fq5Var173;
        fq5 fq5Var174 = new fq5("TEST_BOOLEAN_KEY", 173, "boolean_key", sq5Var5);
        TEST_BOOLEAN_KEY = fq5Var174;
        fq5 fq5Var175 = new fq5("TEST_BOOLEAN_KEY_2", 174, "boolean_key_2", sq5Var5);
        TEST_BOOLEAN_KEY_2 = fq5Var175;
        fq5 fq5Var176 = new fq5("TEST_MAP_KEY", 175, "map_key", sq5Var3);
        TEST_MAP_KEY = fq5Var176;
        fq5 fq5Var177 = new fq5("TEST_LIST_KEY", 176, "list_key", sq5Var);
        TEST_LIST_KEY = fq5Var177;
        fq5 fq5Var178 = new fq5("TEST_ENUM_STRING_KEY", 177, "cached_configuration_provider_test_enum_string", sq5Var4);
        TEST_ENUM_STRING_KEY = fq5Var178;
        fq5 fq5Var179 = new fq5("TEST_STRING_SET_KEY", 178, "cached_configuration_provider_test_string_set", sq5Var);
        TEST_STRING_SET_KEY = fq5Var179;
        fq5[] fq5VarArr = {fq5Var, fq5Var2, fq5Var3, fq5Var4, fq5Var5, fq5Var6, fq5Var7, fq5Var8, fq5Var9, fq5Var10, fq5Var11, fq5Var12, fq5Var13, fq5Var14, fq5Var15, fq5Var16, fq5Var17, fq5Var18, fq5Var19, fq5Var20, fq5Var21, fq5Var22, fq5Var23, fq5Var24, fq5Var25, fq5Var26, fq5Var27, fq5Var28, fq5Var29, fq5Var30, fq5Var31, fq5Var32, fq5Var33, fq5Var34, fq5Var35, fq5Var36, fq5Var37, fq5Var38, fq5Var39, fq5Var40, fq5Var41, fq5Var42, fq5Var43, fq5Var44, fq5Var45, fq5Var46, fq5Var47, fq5Var48, fq5Var49, fq5Var50, fq5Var51, fq5Var52, fq5Var53, fq5Var54, fq5Var55, fq5Var56, fq5Var57, fq5Var58, fq5Var59, fq5Var60, fq5Var61, fq5Var62, fq5Var63, fq5Var64, fq5Var65, fq5Var66, fq5Var67, fq5Var68, fq5Var69, fq5Var70, fq5Var71, fq5Var72, fq5Var73, fq5Var74, fq5Var75, fq5Var76, fq5Var77, fq5Var78, fq5Var79, fq5Var80, fq5Var81, fq5Var82, fq5Var83, fq5Var84, fq5Var85, fq5Var86, fq5Var87, fq5Var88, fq5Var89, fq5Var90, fq5Var91, fq5Var92, fq5Var93, fq5Var94, fq5Var95, fq5Var96, fq5Var97, fq5Var98, fq5Var99, fq5Var100, fq5Var101, fq5Var102, fq5Var103, fq5Var104, fq5Var105, fq5Var106, fq5Var107, fq5Var108, fq5Var109, fq5Var110, fq5Var111, fq5Var112, fq5Var113, fq5Var114, fq5Var115, fq5Var116, fq5Var117, fq5Var118, fq5Var119, fq5Var120, fq5Var121, fq5Var122, fq5Var123, fq5Var124, fq5Var125, fq5Var126, fq5Var127, fq5Var128, fq5Var129, fq5Var130, fq5Var131, fq5Var132, fq5Var133, fq5Var134, fq5Var135, fq5Var136, fq5Var137, fq5Var138, fq5Var139, fq5Var140, fq5Var141, fq5Var142, fq5Var143, fq5Var144, fq5Var145, fq5Var146, fq5Var147, fq5Var148, fq5Var149, fq5Var150, fq5Var151, fq5Var152, fq5Var153, fq5Var154, fq5Var155, fq5Var156, fq5Var157, fq5Var158, fq5Var159, fq5Var160, fq5Var161, fq5Var162, fq5Var163, fq5Var164, fq5Var165, fq5Var166, fq5Var167, fq5Var168, fq5Var169, fq5Var170, fq5Var171, fq5Var172, fq5Var173, fq5Var174, fq5Var175, fq5Var176, fq5Var177, fq5Var178, fq5Var179};
        $VALUES = fq5VarArr;
        $ENTRIES = new wg7(fq5VarArr);
        Companion = new u4();
        keyMap$delegate = LazyKt.lazy(new k65(10));
    }

    public fq5(String str, int i, String str2, sq5 sq5Var) {
        this.key = str2;
        this.type = sq5Var;
    }

    public static final /* synthetic */ Lazy a() {
        return keyMap$delegate;
    }

    public static final LinkedHashMap d() {
        ug7 ug7Var = $ENTRIES;
        int a = c1c.a(CollectionsKt.w(ug7Var));
        if (a < 16) {
            a = 16;
        }
        LinkedHashMap linkedHashMap = new LinkedHashMap(a);
        for (Object obj : ug7Var) {
            linkedHashMap.put(((fq5) obj).key, obj);
        }
        return linkedHashMap;
    }

    public static fq5 valueOf(String str) {
        return (fq5) Enum.valueOf(fq5.class, str);
    }

    public static fq5[] values() {
        return (fq5[]) $VALUES.clone();
    }

    public final String b() {
        return this.key;
    }

    public final sq5 c() {
        return this.type;
    }
}
