package defpackage;

import com.checkout.components.interfaces.model.contact.Country;
import java.util.List;
import kotlin.collections.CollectionsKt;

/* compiled from: r8-map-id-826db3e0ccd5eff4e36cfb5c0bfeee0451562e7e7652a4d6d90edd453ef96714 */
/* loaded from: classes.dex */
public abstract class ky4 {
    public static final List a = CollectionsKt.listOf(Country.ALBANIA, Country.ALGERIA, Country.AMERICAN_SAMOA, Country.ANDORRA, Country.ANGOLA, Country.ANGUILLA, Country.ANTIGUA_AND_BARBUDA, Country.ARGENTINA, Country.ARUBA, Country.AUSTRIA, Country.AZERBAIJAN, Country.BAHRAIN, Country.BARBADOS, Country.BELIZE, Country.BERMUDA, Country.BHUTAN, Country.BOLIVIA, Country.BOSNIA_AND_HERZEGOVINA, Country.BOTSWANA, Country.BRUNEI_DARUSSALAM, Country.BULGARIA, Country.BURKINA_FASO, Country.CAPE_VERDE, Country.CENTRAL_AFRICAN_REPUBLIC, Country.COMOROS, Country.COOK_ISLANDS, Country.CROATIA, Country.CYPRUS, Country.CZECH_REPUBLIC, Country.DENMARK, Country.DJIBOUTI, Country.DOMINICA, Country.EGYPT, Country.EQUATORIAL_GUINEA, Country.ESTONIA, Country.FALKLAND_ISLANDS, Country.FAROE_ISLANDS, Country.FIJI, Country.FINLAND, Country.FRANCE, Country.FRENCH_POLYNESIA, Country.GABON, Country.GAMBIA, Country.GEORGIA, Country.GERMANY, Country.GIBRALTAR, Country.GREECE, Country.GREENLAND, Country.GRENADA, Country.GUADELOUPE, Country.GUATEMALA, Country.GUERNSEY, Country.GUYANA, Country.HAITI, Country.HONDURAS, Country.ICELAND, Country.INDONESIA, Country.IRELAND, Country.ISLE_OF_MAN, Country.ISRAEL, Country.ITALY, Country.JAMAICA, Country.JERSEY, Country.KYRGYZSTAN, Country.LAO_PDR, Country.LATVIA, Country.LEBANON, Country.LESOTHO, Country.LIECHTENSTEIN, Country.LITHUANIA, Country.LUXEMBOURG, Country.MACAO, Country.MADAGASCAR, Country.MALAWI, Country.MALDIVES, Country.MALI, Country.MALTA, Country.MARTINIQUE, Country.MAURITANIA, Country.MAURITIUS, Country.MEXICO, Country.MOLDOVA, Country.MONACO, Country.MONGOLIA, Country.MONTENEGRO, Country.MONTSERRAT, Country.MOZAMBIQUE, Country.NAMIBIA, Country.NETHERLANDS, Country.NEW_CALEDONIA, Country.NIGER, Country.MACEDONIA, Country.NORWAY, Country.OMAN, Country.PAKISTAN, Country.PAPUA_NEW_GUINEA, Country.POLAND, Country.PORTUGAL, Country.QATAR, Country.REUNION, Country.SAINT_KITTS_AND_NEVIS, Country.SAINT_LUCIA, Country.SAINT_VINCENT_AND_GRENADINES, Country.SAMOA, Country.SAN_MARINO, Country.SAO_TOME_AND_PRINCIPE, Country.SAUDI_ARABIA, Country.SENEGAL, Country.SEYCHELLES, Country.SIERRA_LEONE, Country.SLOVAKIA, Country.SLOVENIA, Country.SOLOMON_ISLANDS, Country.SPAIN, Country.SURINAME, Country.SWEDEN, Country.SWITZERLAND, Country.TAJIKISTAN, Country.THAILAND, Country.TIMOR_LESTE, Country.TOGO, Country.TONGA, Country.TRINIDAD_AND_TOBAGO, Country.TURKEY, Country.TURKMENISTAN, Country.TURKS_AND_CAICOS_ISLANDS, Country.UKRAINE, Country.UNITED_ARAB_EMIRATES, Country.UNITED_KINGDOM, Country.UNITED_STATES_OF_AMERICA, Country.UZBEKISTAN, Country.VANUATU, Country.BRITISH_VIRGIN_ISLANDS);
}
