package defpackage;

/* compiled from: r8-map-id-826db3e0ccd5eff4e36cfb5c0bfeee0451562e7e7652a4d6d90edd453ef96714 */
/* loaded from: classes.dex */
public abstract class qb4 {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final long S;
    public static final long T;
    public static final long U;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = std.w;
        a = j2;
        b = std.e;
        c = std.f;
        d = std.u;
        long j3 = std.G;
        e = j3;
        f = std.l;
        long j4 = std.h;
        g = j4;
        h = std.b;
        i = std.a;
        j = std.D;
        long j5 = std.C;
        k = j5;
        l = j5;
        m = std.E;
        n = std.J;
        long j6 = std.I;
        o = j6;
        p = j6;
        q = std.L;
        r = j4;
        s = std.x;
        t = std.Q;
        long j7 = std.P;
        u = j7;
        v = j7;
        w = std.S;
        x = std.y;
        y = std.A;
        z = std.F;
        long j8 = std.H;
        A = j8;
        B = j8;
        C = j3;
        D = std.g;
        E = std.M;
        long j9 = std.O;
        F = j9;
        G = j9;
        H = std.N;
        I = j2;
        J = j2;
        K = std.t;
        L = std.s;
        M = std.r;
        N = std.v;
        O = std.i;
        P = std.q;
        Q = std.B;
        R = std.T;
        long j10 = std.V;
        S = j10;
        T = j10;
        U = std.U;
    }
}
