package defpackage;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* compiled from: r8-map-id-826db3e0ccd5eff4e36cfb5c0bfeee0451562e7e7652a4d6d90edd453ef96714 */
/* loaded from: classes6.dex */
public final class sj7 {
    private static final /* synthetic */ ug7 $ENTRIES;
    private static final /* synthetic */ sj7[] $VALUES;
    public static final sj7 AD_HOC_ERROR_TYPE_FOR_LIGHTER_CLASSES_RESOLVE;
    public static final sj7 CANNOT_COMPUTE_ERASED_BOUND;
    public static final sj7 CANNOT_LOAD_DESERIALIZE_TYPE_PARAMETER;
    public static final sj7 CANNOT_LOAD_DESERIALIZE_TYPE_PARAMETER_BY_NAME;
    public static final sj7 CYCLIC_SUPERTYPES;
    public static final sj7 CYCLIC_UPPER_BOUNDS;
    public static final sj7 DONT_CARE;
    public static final sj7 EMPTY_CALLABLE_REFERENCE;
    public static final sj7 ERROR_CLASS;
    public static final sj7 ERROR_CONSTANT_VALUE;
    public static final sj7 ERROR_DATA_FLOW_TYPE;
    public static final sj7 ERROR_ENUM_TYPE;
    public static final sj7 ERROR_EXPECTED_TYPE;
    public static final sj7 ERROR_EXPRESSION_TYPE;
    public static final sj7 ERROR_FLEXIBLE_TYPE;
    public static final sj7 ERROR_PROPERTY_TYPE;
    public static final sj7 ERROR_RAW_TYPE;
    public static final sj7 ERROR_RECEIVER_TYPE;
    public static final sj7 ERROR_SUPER_TYPE;
    public static final sj7 ERROR_TYPE_FOR_DESTRUCTURING_COMPONENT;
    public static final sj7 ERROR_TYPE_PARAMETER;
    public static final sj7 ERROR_TYPE_PROJECTION;
    public static final sj7 ERROR_WHILE_RECONSTRUCTING_BARE_TYPE;
    public static final sj7 FUNCTION_PLACEHOLDER_TYPE;
    public static final sj7 ILLEGAL_TYPE_RANGE_FOR_DYNAMIC;
    public static final sj7 IMPLICIT_RETURN_TYPE_FOR_FUNCTION;
    public static final sj7 IMPLICIT_RETURN_TYPE_FOR_PROPERTY;
    public static final sj7 IMPLICIT_RETURN_TYPE_FOR_PROPERTY_ACCESSOR;
    public static final sj7 INCONSISTENT_SUSPEND_FUNCTION;
    public static final sj7 INTERSECTION_OF_ERROR_TYPES;
    public static final sj7 KAPT_ERROR_TYPE;
    public static final sj7 MISSED_TYPE_ARGUMENT_FOR_TYPE_PARAMETER;
    public static final sj7 MISSED_TYPE_FOR_PARAMETER;
    public static final sj7 NOT_ANNOTATION_TYPE_IN_ANNOTATION_CONTEXT;
    public static final sj7 NOT_FOUND_DESCRIPTOR_FOR_CLASS;
    public static final sj7 NOT_FOUND_DESCRIPTOR_FOR_FUNCTION;
    public static final sj7 NOT_FOUND_DESCRIPTOR_FOR_TYPE_PARAMETER;
    public static final sj7 NOT_FOUND_FQNAME;
    public static final sj7 NOT_FOUND_FQNAME_FOR_JAVA_ANNOTATION;
    public static final sj7 NOT_FOUND_UNSIGNED_TYPE;
    public static final sj7 NO_RECORDED_TYPE;
    public static final sj7 NO_TYPE_FOR_LOOP_PARAMETER;
    public static final sj7 NO_TYPE_FOR_LOOP_RANGE;
    public static final sj7 NO_TYPE_SPECIFIED;
    public static final sj7 PARSE_ERROR_ARGUMENT;
    public static final sj7 PROHIBITED_DYNAMIC_TYPE;
    public static final sj7 RECURSIVE_ANNOTATION_TYPE;
    public static final sj7 RECURSIVE_TYPE;
    public static final sj7 RECURSIVE_TYPE_ALIAS;
    public static final sj7 RESOLUTION_ERROR_TYPE;
    public static final sj7 RETURN_NOT_ALLOWED;
    public static final sj7 RETURN_TYPE;
    public static final sj7 RETURN_TYPE_FOR_CONSTRUCTOR;
    public static final sj7 RETURN_TYPE_FOR_FUNCTION;
    public static final sj7 RETURN_TYPE_FOR_PROPERTY;
    public static final sj7 STAR_PROJECTION_IN_CALL;
    public static final sj7 STUB_TYPE;
    public static final sj7 SUPER_TYPE_FOR_ERROR_TYPE;
    public static final sj7 SYNTHETIC_ELEMENT_ERROR_TYPE;
    public static final sj7 TYPE_FOR_COMPILER_EXCEPTION;
    public static final sj7 TYPE_FOR_DELEGATION;
    public static final sj7 TYPE_FOR_ERROR_TYPE_CONSTRUCTOR;
    public static final sj7 TYPE_FOR_GENERATED_ERROR_EXPRESSION;
    public static final sj7 TYPE_WITH_MISMATCHED_TYPE_ARGUMENTS_AND_PARAMETERS;
    public static final sj7 UNABLE_TO_SUBSTITUTE_TYPE;
    public static final sj7 UNAVAILABLE_TYPE_FOR_DECLARATION;
    public static final sj7 UNEXPECTED_FLEXIBLE_TYPE_ID;
    public static final sj7 UNINFERRED_LAMBDA_CONTEXT_RECEIVER_TYPE;
    public static final sj7 UNINFERRED_LAMBDA_PARAMETER_TYPE;
    public static final sj7 UNINFERRED_TYPE_VARIABLE;
    public static final sj7 UNIT_RETURN_TYPE_FOR_INC_DEC;
    public static final sj7 UNKNOWN_ARRAY_ELEMENT_TYPE_OF_ANNOTATION_ARGUMENT;
    public static final sj7 UNKNOWN_TYPE;
    public static final sj7 UNMAPPED_ANNOTATION_TARGET_TYPE;
    public static final sj7 UNRESOLVED_CLASS_TYPE;
    public static final sj7 UNRESOLVED_DECLARATION;
    public static final sj7 UNRESOLVED_JAVA_CLASS;
    public static final sj7 UNRESOLVED_KCLASS_CONSTANT_VALUE;
    public static final sj7 UNRESOLVED_PARCEL_TYPE;
    public static final sj7 UNRESOLVED_TYPE;
    public static final sj7 UNRESOLVED_TYPE_ALIAS;
    public static final sj7 UNRESOLVED_TYPE_PARAMETER_TYPE;
    public static final sj7 UNSUPPORTED_CALLABLE_REFERENCE_TYPE;
    private final String debugMessage;
    private final boolean isUnresolved;

    static {
        sj7 sj7Var = new sj7(0, "UNRESOLVED_TYPE", true, "Unresolved type for %s");
        UNRESOLVED_TYPE = sj7Var;
        sj7 sj7Var2 = new sj7(1, "UNRESOLVED_TYPE_PARAMETER_TYPE", true, "Unresolved type parameter type");
        UNRESOLVED_TYPE_PARAMETER_TYPE = sj7Var2;
        sj7 sj7Var3 = new sj7(2, "UNRESOLVED_CLASS_TYPE", true, "Unresolved class %s");
        UNRESOLVED_CLASS_TYPE = sj7Var3;
        sj7 sj7Var4 = new sj7(3, "UNRESOLVED_JAVA_CLASS", true, "Unresolved java class %s");
        UNRESOLVED_JAVA_CLASS = sj7Var4;
        sj7 sj7Var5 = new sj7(4, "UNRESOLVED_DECLARATION", true, "Unresolved declaration %s");
        UNRESOLVED_DECLARATION = sj7Var5;
        sj7 sj7Var6 = new sj7(5, "UNRESOLVED_KCLASS_CONSTANT_VALUE", true, "Unresolved type for %s (arrayDimensions=%s)");
        UNRESOLVED_KCLASS_CONSTANT_VALUE = sj7Var6;
        sj7 sj7Var7 = new sj7(6, "UNRESOLVED_TYPE_ALIAS", false, "Unresolved type alias %s");
        UNRESOLVED_TYPE_ALIAS = sj7Var7;
        sj7 sj7Var8 = new sj7(7, "RETURN_TYPE", false, "Return type for %s cannot be resolved");
        RETURN_TYPE = sj7Var8;
        sj7 sj7Var9 = new sj7(8, "RETURN_TYPE_FOR_FUNCTION", false, "Return type for function cannot be resolved");
        RETURN_TYPE_FOR_FUNCTION = sj7Var9;
        sj7 sj7Var10 = new sj7(9, "RETURN_TYPE_FOR_PROPERTY", false, "Return type for property %s cannot be resolved");
        RETURN_TYPE_FOR_PROPERTY = sj7Var10;
        sj7 sj7Var11 = new sj7(10, "RETURN_TYPE_FOR_CONSTRUCTOR", false, "Return type for constructor %s cannot be resolved");
        RETURN_TYPE_FOR_CONSTRUCTOR = sj7Var11;
        sj7 sj7Var12 = new sj7(11, "IMPLICIT_RETURN_TYPE_FOR_FUNCTION", false, "Implicit return type for function %s cannot be resolved");
        IMPLICIT_RETURN_TYPE_FOR_FUNCTION = sj7Var12;
        sj7 sj7Var13 = new sj7(12, "IMPLICIT_RETURN_TYPE_FOR_PROPERTY", false, "Implicit return type for property %s cannot be resolved");
        IMPLICIT_RETURN_TYPE_FOR_PROPERTY = sj7Var13;
        sj7 sj7Var14 = new sj7(13, "IMPLICIT_RETURN_TYPE_FOR_PROPERTY_ACCESSOR", false, "Implicit return type for property accessor %s cannot be resolved");
        IMPLICIT_RETURN_TYPE_FOR_PROPERTY_ACCESSOR = sj7Var14;
        sj7 sj7Var15 = new sj7(14, "ERROR_TYPE_FOR_DESTRUCTURING_COMPONENT", false, "%s() return type");
        ERROR_TYPE_FOR_DESTRUCTURING_COMPONENT = sj7Var15;
        sj7 sj7Var16 = new sj7(15, "RECURSIVE_TYPE", false, "Recursive type");
        RECURSIVE_TYPE = sj7Var16;
        sj7 sj7Var17 = new sj7(16, "RECURSIVE_TYPE_ALIAS", false, "Recursive type alias %s");
        RECURSIVE_TYPE_ALIAS = sj7Var17;
        sj7 sj7Var18 = new sj7(17, "RECURSIVE_ANNOTATION_TYPE", false, "Recursive annotation's type");
        RECURSIVE_ANNOTATION_TYPE = sj7Var18;
        sj7 sj7Var19 = new sj7(18, "CYCLIC_UPPER_BOUNDS", false, "Cyclic upper bounds");
        CYCLIC_UPPER_BOUNDS = sj7Var19;
        sj7 sj7Var20 = new sj7(19, "CYCLIC_SUPERTYPES", false, "Cyclic supertypes");
        CYCLIC_SUPERTYPES = sj7Var20;
        sj7 sj7Var21 = new sj7(20, "UNINFERRED_LAMBDA_CONTEXT_RECEIVER_TYPE", false, "Cannot infer a lambda context receiver type");
        UNINFERRED_LAMBDA_CONTEXT_RECEIVER_TYPE = sj7Var21;
        sj7 sj7Var22 = new sj7(21, "UNINFERRED_LAMBDA_PARAMETER_TYPE", false, "Cannot infer a lambda parameter type");
        UNINFERRED_LAMBDA_PARAMETER_TYPE = sj7Var22;
        sj7 sj7Var23 = new sj7(22, "UNINFERRED_TYPE_VARIABLE", false, "Cannot infer a type variable %s");
        UNINFERRED_TYPE_VARIABLE = sj7Var23;
        sj7 sj7Var24 = new sj7(23, "RESOLUTION_ERROR_TYPE", false, "Resolution error type (%s)");
        RESOLUTION_ERROR_TYPE = sj7Var24;
        sj7 sj7Var25 = new sj7(24, "ERROR_EXPECTED_TYPE", false, "Error expected type");
        ERROR_EXPECTED_TYPE = sj7Var25;
        sj7 sj7Var26 = new sj7(25, "ERROR_DATA_FLOW_TYPE", false, "Error type for data flow");
        ERROR_DATA_FLOW_TYPE = sj7Var26;
        sj7 sj7Var27 = new sj7(26, "ERROR_WHILE_RECONSTRUCTING_BARE_TYPE", false, "Failed to reconstruct type %s");
        ERROR_WHILE_RECONSTRUCTING_BARE_TYPE = sj7Var27;
        sj7 sj7Var28 = new sj7(27, "UNABLE_TO_SUBSTITUTE_TYPE", false, "Unable to substitute type (%s)");
        UNABLE_TO_SUBSTITUTE_TYPE = sj7Var28;
        sj7 sj7Var29 = new sj7(28, "DONT_CARE", false, "Special DONT_CARE type");
        DONT_CARE = sj7Var29;
        sj7 sj7Var30 = new sj7(29, "STUB_TYPE", false, "Stub type %s");
        STUB_TYPE = sj7Var30;
        sj7 sj7Var31 = new sj7(30, "FUNCTION_PLACEHOLDER_TYPE", false, "Function placeholder type (arguments: %s)");
        FUNCTION_PLACEHOLDER_TYPE = sj7Var31;
        sj7 sj7Var32 = new sj7(31, "TYPE_FOR_COMPILER_EXCEPTION", false, "Error type for a compiler exception while analyzing %s");
        TYPE_FOR_COMPILER_EXCEPTION = sj7Var32;
        sj7 sj7Var33 = new sj7(32, "ERROR_FLEXIBLE_TYPE", false, "Error java flexible type with id %s. (%s..%s)");
        ERROR_FLEXIBLE_TYPE = sj7Var33;
        sj7 sj7Var34 = new sj7(33, "ERROR_RAW_TYPE", false, "Error raw type %s");
        ERROR_RAW_TYPE = sj7Var34;
        sj7 sj7Var35 = new sj7(34, "TYPE_WITH_MISMATCHED_TYPE_ARGUMENTS_AND_PARAMETERS", false, "Inconsistent type %s (parameters.size = %s, arguments.size = %s)");
        TYPE_WITH_MISMATCHED_TYPE_ARGUMENTS_AND_PARAMETERS = sj7Var35;
        sj7 sj7Var36 = new sj7(35, "ILLEGAL_TYPE_RANGE_FOR_DYNAMIC", false, "Illegal type range for dynamic type %s..%s");
        ILLEGAL_TYPE_RANGE_FOR_DYNAMIC = sj7Var36;
        sj7 sj7Var37 = new sj7(36, "CANNOT_LOAD_DESERIALIZE_TYPE_PARAMETER", false, "Unknown type parameter %s. Please try recompiling module containing \"%s\"");
        CANNOT_LOAD_DESERIALIZE_TYPE_PARAMETER = sj7Var37;
        sj7 sj7Var38 = new sj7(37, "CANNOT_LOAD_DESERIALIZE_TYPE_PARAMETER_BY_NAME", false, "Couldn't deserialize type parameter %s in %s");
        CANNOT_LOAD_DESERIALIZE_TYPE_PARAMETER_BY_NAME = sj7Var38;
        sj7 sj7Var39 = new sj7(38, "INCONSISTENT_SUSPEND_FUNCTION", false, "Inconsistent suspend function type in metadata with constructor %s");
        INCONSISTENT_SUSPEND_FUNCTION = sj7Var39;
        sj7 sj7Var40 = new sj7(39, "UNEXPECTED_FLEXIBLE_TYPE_ID", false, "Unexpected id of a flexible type %s. (%s..%s)");
        UNEXPECTED_FLEXIBLE_TYPE_ID = sj7Var40;
        sj7 sj7Var41 = new sj7(40, "UNKNOWN_TYPE", false, "Unknown type");
        UNKNOWN_TYPE = sj7Var41;
        sj7 sj7Var42 = new sj7(41, "NO_TYPE_SPECIFIED", false, "No type specified for %s");
        NO_TYPE_SPECIFIED = sj7Var42;
        sj7 sj7Var43 = new sj7(42, "NO_TYPE_FOR_LOOP_RANGE", false, "Loop range has no type");
        NO_TYPE_FOR_LOOP_RANGE = sj7Var43;
        sj7 sj7Var44 = new sj7(43, "NO_TYPE_FOR_LOOP_PARAMETER", false, "Loop parameter has no type");
        NO_TYPE_FOR_LOOP_PARAMETER = sj7Var44;
        sj7 sj7Var45 = new sj7(44, "MISSED_TYPE_FOR_PARAMETER", false, "Missed a type for a value parameter %s");
        MISSED_TYPE_FOR_PARAMETER = sj7Var45;
        sj7 sj7Var46 = new sj7(45, "MISSED_TYPE_ARGUMENT_FOR_TYPE_PARAMETER", false, "Missed a type argument for a type parameter %s");
        MISSED_TYPE_ARGUMENT_FOR_TYPE_PARAMETER = sj7Var46;
        sj7 sj7Var47 = new sj7(46, "PARSE_ERROR_ARGUMENT", false, "Error type for parse error argument %s");
        PARSE_ERROR_ARGUMENT = sj7Var47;
        sj7 sj7Var48 = new sj7(47, "STAR_PROJECTION_IN_CALL", false, "Error type for star projection directly passing as a call type argument");
        STAR_PROJECTION_IN_CALL = sj7Var48;
        sj7 sj7Var49 = new sj7(48, "PROHIBITED_DYNAMIC_TYPE", false, "Dynamic type in a not allowed context");
        PROHIBITED_DYNAMIC_TYPE = sj7Var49;
        sj7 sj7Var50 = new sj7(49, "NOT_ANNOTATION_TYPE_IN_ANNOTATION_CONTEXT", false, "Not an annotation type %s in the annotation context");
        NOT_ANNOTATION_TYPE_IN_ANNOTATION_CONTEXT = sj7Var50;
        sj7 sj7Var51 = new sj7(50, "UNIT_RETURN_TYPE_FOR_INC_DEC", false, "Unit type returned by inc or dec");
        UNIT_RETURN_TYPE_FOR_INC_DEC = sj7Var51;
        sj7 sj7Var52 = new sj7(51, "RETURN_NOT_ALLOWED", false, "Return not allowed");
        RETURN_NOT_ALLOWED = sj7Var52;
        sj7 sj7Var53 = new sj7(52, "UNRESOLVED_PARCEL_TYPE", true, "Unresolved 'Parcel' type");
        UNRESOLVED_PARCEL_TYPE = sj7Var53;
        sj7 sj7Var54 = new sj7(53, "KAPT_ERROR_TYPE", false, "Kapt error type");
        KAPT_ERROR_TYPE = sj7Var54;
        sj7 sj7Var55 = new sj7(54, "SYNTHETIC_ELEMENT_ERROR_TYPE", false, "Error type for synthetic element");
        SYNTHETIC_ELEMENT_ERROR_TYPE = sj7Var55;
        sj7 sj7Var56 = new sj7(55, "AD_HOC_ERROR_TYPE_FOR_LIGHTER_CLASSES_RESOLVE", false, "Error type in ad hoc resolve for lighter classes");
        AD_HOC_ERROR_TYPE_FOR_LIGHTER_CLASSES_RESOLVE = sj7Var56;
        sj7 sj7Var57 = new sj7(56, "ERROR_EXPRESSION_TYPE", false, "Error expression type");
        ERROR_EXPRESSION_TYPE = sj7Var57;
        sj7 sj7Var58 = new sj7(57, "ERROR_RECEIVER_TYPE", false, "Error receiver type for %s");
        ERROR_RECEIVER_TYPE = sj7Var58;
        sj7 sj7Var59 = new sj7(58, "ERROR_CONSTANT_VALUE", false, "Error constant value %s");
        ERROR_CONSTANT_VALUE = sj7Var59;
        sj7 sj7Var60 = new sj7(59, "EMPTY_CALLABLE_REFERENCE", false, "Empty callable reference");
        EMPTY_CALLABLE_REFERENCE = sj7Var60;
        sj7 sj7Var61 = new sj7(60, "UNSUPPORTED_CALLABLE_REFERENCE_TYPE", false, "Unsupported callable reference type %s");
        UNSUPPORTED_CALLABLE_REFERENCE_TYPE = sj7Var61;
        sj7 sj7Var62 = new sj7(61, "TYPE_FOR_DELEGATION", false, "Error delegation type for %s");
        TYPE_FOR_DELEGATION = sj7Var62;
        sj7 sj7Var63 = new sj7(62, "UNAVAILABLE_TYPE_FOR_DECLARATION", false, "Type is unavailable for declaration %s");
        UNAVAILABLE_TYPE_FOR_DECLARATION = sj7Var63;
        sj7 sj7Var64 = new sj7(63, "ERROR_TYPE_PARAMETER", false, "Error type parameter");
        ERROR_TYPE_PARAMETER = sj7Var64;
        sj7 sj7Var65 = new sj7(64, "ERROR_TYPE_PROJECTION", false, "Error type projection");
        ERROR_TYPE_PROJECTION = sj7Var65;
        sj7 sj7Var66 = new sj7(65, "ERROR_SUPER_TYPE", false, "Error super type");
        ERROR_SUPER_TYPE = sj7Var66;
        sj7 sj7Var67 = new sj7(66, "SUPER_TYPE_FOR_ERROR_TYPE", false, "Supertype of error type %s");
        SUPER_TYPE_FOR_ERROR_TYPE = sj7Var67;
        sj7 sj7Var68 = new sj7(67, "ERROR_PROPERTY_TYPE", false, "Error property type");
        ERROR_PROPERTY_TYPE = sj7Var68;
        sj7 sj7Var69 = new sj7(68, "ERROR_CLASS", false, "Error class");
        ERROR_CLASS = sj7Var69;
        sj7 sj7Var70 = new sj7(69, "TYPE_FOR_ERROR_TYPE_CONSTRUCTOR", false, "Type for error type constructor (%s)");
        TYPE_FOR_ERROR_TYPE_CONSTRUCTOR = sj7Var70;
        sj7 sj7Var71 = new sj7(70, "INTERSECTION_OF_ERROR_TYPES", false, "Intersection of error types %s");
        INTERSECTION_OF_ERROR_TYPES = sj7Var71;
        sj7 sj7Var72 = new sj7(71, "CANNOT_COMPUTE_ERASED_BOUND", false, "Cannot compute erased upper bound of a type parameter %s");
        CANNOT_COMPUTE_ERASED_BOUND = sj7Var72;
        sj7 sj7Var73 = new sj7(72, "NOT_FOUND_UNSIGNED_TYPE", false, "Unsigned type %s not found");
        NOT_FOUND_UNSIGNED_TYPE = sj7Var73;
        sj7 sj7Var74 = new sj7(73, "ERROR_ENUM_TYPE", false, "Not found the corresponding enum class for given enum entry %s.%s");
        ERROR_ENUM_TYPE = sj7Var74;
        sj7 sj7Var75 = new sj7(74, "NO_RECORDED_TYPE", false, "Not found recorded type for %s");
        NO_RECORDED_TYPE = sj7Var75;
        sj7 sj7Var76 = new sj7(75, "NOT_FOUND_DESCRIPTOR_FOR_FUNCTION", false, "Descriptor not found for function %s");
        NOT_FOUND_DESCRIPTOR_FOR_FUNCTION = sj7Var76;
        sj7 sj7Var77 = new sj7(76, "NOT_FOUND_DESCRIPTOR_FOR_CLASS", false, "Cannot build class type, descriptor not found for builder %s");
        NOT_FOUND_DESCRIPTOR_FOR_CLASS = sj7Var77;
        sj7 sj7Var78 = new sj7(77, "NOT_FOUND_DESCRIPTOR_FOR_TYPE_PARAMETER", false, "Cannot build type parameter type, descriptor not found for builder %s");
        NOT_FOUND_DESCRIPTOR_FOR_TYPE_PARAMETER = sj7Var78;
        sj7 sj7Var79 = new sj7(78, "UNMAPPED_ANNOTATION_TARGET_TYPE", false, "Type for unmapped Java annotation target to Kotlin one");
        UNMAPPED_ANNOTATION_TARGET_TYPE = sj7Var79;
        sj7 sj7Var80 = new sj7(79, "UNKNOWN_ARRAY_ELEMENT_TYPE_OF_ANNOTATION_ARGUMENT", false, "Unknown type for an array element of a java annotation argument");
        UNKNOWN_ARRAY_ELEMENT_TYPE_OF_ANNOTATION_ARGUMENT = sj7Var80;
        sj7 sj7Var81 = new sj7(80, "NOT_FOUND_FQNAME_FOR_JAVA_ANNOTATION", false, "No fqName for annotation %s");
        NOT_FOUND_FQNAME_FOR_JAVA_ANNOTATION = sj7Var81;
        sj7 sj7Var82 = new sj7(81, "NOT_FOUND_FQNAME", false, "No fqName for %s");
        NOT_FOUND_FQNAME = sj7Var82;
        sj7 sj7Var83 = new sj7(82, "TYPE_FOR_GENERATED_ERROR_EXPRESSION", false, "Type for generated error expression");
        TYPE_FOR_GENERATED_ERROR_EXPRESSION = sj7Var83;
        sj7[] sj7VarArr = {sj7Var, sj7Var2, sj7Var3, sj7Var4, sj7Var5, sj7Var6, sj7Var7, sj7Var8, sj7Var9, sj7Var10, sj7Var11, sj7Var12, sj7Var13, sj7Var14, sj7Var15, sj7Var16, sj7Var17, sj7Var18, sj7Var19, sj7Var20, sj7Var21, sj7Var22, sj7Var23, sj7Var24, sj7Var25, sj7Var26, sj7Var27, sj7Var28, sj7Var29, sj7Var30, sj7Var31, sj7Var32, sj7Var33, sj7Var34, sj7Var35, sj7Var36, sj7Var37, sj7Var38, sj7Var39, sj7Var40, sj7Var41, sj7Var42, sj7Var43, sj7Var44, sj7Var45, sj7Var46, sj7Var47, sj7Var48, sj7Var49, sj7Var50, sj7Var51, sj7Var52, sj7Var53, sj7Var54, sj7Var55, sj7Var56, sj7Var57, sj7Var58, sj7Var59, sj7Var60, sj7Var61, sj7Var62, sj7Var63, sj7Var64, sj7Var65, sj7Var66, sj7Var67, sj7Var68, sj7Var69, sj7Var70, sj7Var71, sj7Var72, sj7Var73, sj7Var74, sj7Var75, sj7Var76, sj7Var77, sj7Var78, sj7Var79, sj7Var80, sj7Var81, sj7Var82, sj7Var83};
        $VALUES = sj7VarArr;
        $ENTRIES = new wg7(sj7VarArr);
    }

    public sj7(int i, String str, boolean z, String str2) {
        this.debugMessage = str2;
        this.isUnresolved = z;
    }

    public static sj7 valueOf(String str) {
        return (sj7) Enum.valueOf(sj7.class, str);
    }

    public static sj7[] values() {
        return (sj7[]) $VALUES.clone();
    }

    public final String a() {
        return this.debugMessage;
    }

    public final boolean b() {
        return this.isUnresolved;
    }
}
